// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "// PHASE 9B (Virtual Pet migration): this file is the LOCAL persistence"
// legacy-line: "// adapter connecting the shared `@mrburdeveloperteam/pet-function/pet`"
// legacy-line: "// runtime to App Gallery's OWN existing database. It implements the"
// legacy-line: "// package's `PetRepository` interface — the shared runtime only ever calls"
// legacy-line: "// these methods, never `supabase` directly. Every query here is moved"
// legacy-line: "// mechanically from `VirtualPet/context/GameStateContext.tsx` (and"
// legacy-line: "// `VirtualPetContainer.tsx`'s catalog/currency lookups) — confirmed"
// legacy-line: "// byte-identical (same table names, same column names, same decay/XP/coin"
// legacy-line: "// constants, same soap/soap2-exclusion, same toy-quantity-clamp, same"
// legacy-line: "// adoption-seeding branch) to the installed shared package's own internal"
// legacy-line: "// runtime (verified directly against `dist/pet.js`), matching every other"
// legacy-line: "// migrated app's own `xxxPetRepository.ts` in this migration series:"
// legacy-line: "//   - inventory_pet     (pet stats/identity snapshot, one row per user)"
// legacy-line: "//   - pet_inventory     (owned items, full delete-then-insert sync)"
// legacy-line: "//   - aiboard_pricing_items      (flat shop catalog)"
// legacy-line: "//   - aiboard_pricing_currencies (currency code -> rate lookup)"
// legacy-line: "//"
// legacy-line: "// This is intentionally the ONLY file in App Gallery that imports both"
// legacy-line: "// `@mrburdeveloperteam/pet-function/contracts` types and the Supabase"
// legacy-line: "// client for pet data — the shared package itself must never see any of"
// legacy-line: "// these table names."
// legacy-line: "import type { PetRepository } from '@mrburdeveloperteam/pet-function/contracts';"
// legacy-line: "import type { FoodItem, PetInventoryItem, PetSaveSnapshot } from '@mrburdeveloperteam/pet-function/contracts';"
// legacy-line: "import { supabase } from '../services/supabaseClient';"
// legacy-line: ""
// legacy-line: "type PricingItemRow = {"
// legacy-line: "  id: string;"
// legacy-line: "  user_id: string | null;"
// legacy-line: "  item_id: string;"
// legacy-line: "  name: string;"
// legacy-line: "  emoji?: string | null;"
// legacy-line: "  category_id?: string | null;"
// legacy-line: "  base_price_usd?: string | number | null;"
// legacy-line: "  hunger?: number | null;"
// legacy-line: "  happiness?: number | null;"
// legacy-line: "  hygiene?: number | null;"
// legacy-line: "  energy_gain?: number | null;"
// legacy-line: "  image_src?: string | null;"
// legacy-line: "  unlock_level?: number | null;"
// legacy-line: "};"
// legacy-line: ""
// legacy-line: "// UNKNOWN != ZERO: base_price_usd is nullable/free-text at the DB level, so"
// legacy-line: "// an explicit numeric 0 (a genuinely free item) must be told apart from"
// legacy-line: "// missing/malformed data. `Number()` (not `parseFloat`) is used because"
// legacy-line: "// `parseFloat` accepts partial matches like \"12abc\" -> 12, and"
// legacy-line: "// `Number('')` -> 0 is special-cased below since it would otherwise"
// legacy-line: "// silently pass as a valid zero."
// legacy-line: "function parseCatalogPrice(raw: PricingItemRow['base_price_usd']): number {"
// legacy-line: "  return raw === null || raw === undefined || raw === '' ? NaN : Number(raw);"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "type PetInventoryRow = {"
// legacy-line: "  item_id: string;"
// legacy-line: "  quantity: number;"
// legacy-line: "};"
// legacy-line: ""
// legacy-line: "type InventoryPetRow = {"
// legacy-line: "  pet_name: string | null;"
// legacy-line: "  hunger: number | null;"
// legacy-line: "  energy: number | null;"
// legacy-line: "  happiness: number | null;"
// legacy-line: "  hygiene: number | null;"
// legacy-line: "  level: number | null;"
// legacy-line: "  xp: number | null;"
// legacy-line: "  coins: number | null;"
// legacy-line: "  is_sleeping: boolean | null;"
// legacy-line: "  active_ball_id: string | null;"
// legacy-line: "  active_bed_id: string | null;"
// legacy-line: "  updated_at: string | null;"
// legacy-line: "};"
// legacy-line: ""
// legacy-line: "export const appGalleryPetRepository: PetRepository = {"
// legacy-line: "  async loadSnapshot(userId: string): Promise<PetSaveSnapshot | null> {"
// legacy-line: "    const { data, error } = await supabase"
// legacy-line: "      .from('inventory_pet')"
// legacy-line: "      .select('*')"
// legacy-line: "      .eq('user_id', userId)"
// legacy-line: "      .maybeSingle();"
// legacy-line: ""
// legacy-line: "    if (error) {"
// legacy-line: "      // Verified against the installed 0.5.0 runtime (`pet.js`'s init"
// legacy-line: "      // sequence): a rejected `loadSnapshot` is caught by the shared"
// legacy-line: "      // runtime's own outer try/catch there and simply logged — it does"
// legacy-line: "      // NOT fall into the \"no petData\" starter/adoption-reset branch"
// legacy-line: "      // (that branch only triggers on a resolved `null`). Returning"
// legacy-line: "      // `null` here instead would be indistinguishable from a genuine"
// legacy-line: "      // no-row (never-adopted) result, which DOES trigger that reset —"
// legacy-line: "      // collapsing a transient query error into false adoption."
// legacy-line: "      console.error('[appGalleryPetRepository] Failed to load inventory_pet:', error);"
// legacy-line: "      throw error;"
// legacy-line: "    }"
// legacy-line: "    if (!data) return null;"
// legacy-line: ""
// legacy-line: "    const row = data as InventoryPetRow;"
// legacy-line: "    return {"
// legacy-line: "      globalUserId: userId,"
// legacy-line: "      stats: {"
// legacy-line: "        hunger: row.hunger ?? 100,"
// legacy-line: "        energy: row.energy ?? 100,"
// legacy-line: "        happiness: row.happiness ?? 100,"
// legacy-line: "        hygiene: row.hygiene ?? 100,"
// legacy-line: "        level: row.level ?? 1,"
// legacy-line: "        xp: row.xp ?? 0,"
// legacy-line: "        coins: row.coins ?? 100,"
// legacy-line: "      },"
// legacy-line: "      identity: {"
// legacy-line: "        // Empty string means \"not adopted yet\" — matches the runtime's"
// legacy-line: "        // exact falsy check against the original `pet_name` column."
// legacy-line: "        petName: row.pet_name ?? '',"
// legacy-line: "        selectedPetId: row.pet_name ?? '',"
// legacy-line: "        isSleeping: !!row.is_sleeping,"
// legacy-line: "        activeBallId: row.active_ball_id ?? null,"
// legacy-line: "        activeBedId: row.active_bed_id ?? null,"
// legacy-line: "      },"
// legacy-line: "      updatedAt: row.updated_at ?? new Date(0).toISOString(),"
// legacy-line: "    };"
// legacy-line: "  },"
// legacy-line: ""
// legacy-line: "  async saveSnapshot(snapshot: PetSaveSnapshot): Promise<void> {"
// legacy-line: "    // Atomic snapshot upsert RPC (Phase"
// legacy-line: "    // SNABBB-SHARED-VIRTUAL-PET-COINS-CONCURRENCY-HARDENING) — replaces"
// legacy-line: "    // the prior raw `.upsert()`, which wrote `coins` as an absolute"
// legacy-line: "    // value on every call, including this routine debounced call that"
// legacy-line: "    // fires on ANY stat change (not just coin activity). See"
// legacy-line: "    // public.save_pet_snapshot's own definition: `coins` is accepted"
// legacy-line: "    // only to seed a brand-new row on first adoption and is otherwise a"
// legacy-line: "    // guaranteed no-op — coins are managed exclusively by"
// legacy-line: "    // `mutateCoins`/`purchasePetItem`'s atomic deltas below."
// legacy-line: "    const { error } = await supabase.rpc('save_pet_snapshot', {"
// legacy-line: "      p_pet_name: snapshot.identity.petName || null,"
// legacy-line: "      p_hunger: snapshot.stats.hunger,"
// legacy-line: "      p_energy: snapshot.stats.energy,"
// legacy-line: "      p_happiness: snapshot.stats.happiness,"
// legacy-line: "      p_hygiene: snapshot.stats.hygiene,"
// legacy-line: "      p_level: snapshot.stats.level,"
// legacy-line: "      p_xp: snapshot.stats.xp,"
// legacy-line: "      p_coins: snapshot.stats.coins,"
// legacy-line: "      p_is_sleeping: snapshot.identity.isSleeping,"
// legacy-line: "      p_active_ball_id: snapshot.identity.activeBallId,"
// legacy-line: "      p_active_bed_id: snapshot.identity.activeBedId,"
// legacy-line: "    });"
// legacy-line: "    if (error) throw error;"
// legacy-line: "  },"
// legacy-line: ""
// legacy-line: "  async loadInventoryRows(userId: string): Promise<PetInventoryItem[]> {"
// legacy-line: "    const { data, error } = await supabase"
// legacy-line: "      .from('pet_inventory')"
// legacy-line: "      .select('item_id, quantity')"
// legacy-line: "      .eq('user_id', userId);"
// legacy-line: ""
// legacy-line: "    if (error) {"
// legacy-line: "      // Same rationale as loadSnapshot above: the 0.5.0 runtime's init"
// legacy-line: "      // sequence catches a rejected `loadInventoryRows` and leaves"
// legacy-line: "      // inventory state untouched, so throwing here does not force a"
// legacy-line: "      // genuine-empty-inventory misread the way returning `[]` would."
// legacy-line: "      console.error('[appGalleryPetRepository] Failed to load pet_inventory:', error);"
// legacy-line: "      throw error;"
// legacy-line: "    }"
// legacy-line: ""
// legacy-line: "    return (data as PetInventoryRow[]).map((row) => ({ itemId: row.item_id, quantity: row.quantity }));"
// legacy-line: "  },"
// legacy-line: ""
// legacy-line: "  async saveInventory(userId: string, items: PetInventoryItem[]): Promise<void> {"
// legacy-line: "    // Single atomic upsert+prune RPC (Phase"
// legacy-line: "    // SNABBB-VIRTUAL-PET-INVENTORY-ATOMICITY-AUDIT-AND-HARDENING) —"
// legacy-line: "    // replaces the prior delete-then-insert two-request sequence, which"
// legacy-line: "    // could leave this user's inventory empty if the process failed"
// legacy-line: "    // between the delete and the insert. See public.save_pet_inventory's"
// legacy-line: "    // own definition for the full rationale: it upserts every incoming"
// legacy-line: "    // item (never destroying a row for an item this snapshot didn't"
// legacy-line: "    // know about — e.g. one another app/tab just added) and only prunes"
// legacy-line: "    // rows for items absent from this list, all inside one transaction."
// legacy-line: "    // `auth.uid()` is derived server-side from the caller's own"
// legacy-line: "    // session — this repository has no way to write another user's"
// legacy-line: "    // inventory even if `userId` here were wrong."
// legacy-line: "    const { error } = await supabase.rpc('save_pet_inventory', {"
// legacy-line: "      p_items: items.map((item) => ({ itemId: item.itemId, quantity: item.quantity })),"
// legacy-line: "    });"
// legacy-line: "    if (error) throw error;"
// legacy-line: "  },"
// legacy-line: ""
// legacy-line: "  async mutateInventoryItem(userId: string, itemId: string, delta: number): Promise<number> {"
// legacy-line: "    // Atomic, item-level increment/decrement (Phase"
// legacy-line: "    // SNABBB-SHARED-VIRTUAL-PET-CROSS-APP-CONCURRENCY-HARDENING) — the"
// legacy-line: "    // narrow persistence path SharedPetRuntime now uses for buyItem/"
// legacy-line: "    // consumeItem instead of the full-list saveInventory above. See"
// legacy-line: "    // public.mutate_pet_inventory_item's own definition: a single"
// legacy-line: "    // `UPDATE ... SET quantity = quantity + delta` under Postgres's own"
// legacy-line: "    // row lock, so concurrent calls for the SAME item from another"
// legacy-line: "    // app/tab never lose an update, and calls for a DIFFERENT item"
// legacy-line: "    // never contend at all (they touch a different row). `auth.uid()`"
// legacy-line: "    // is derived server-side — this repository has no way to mutate"
// legacy-line: "    // another user's inventory even if `userId` here were wrong."
// legacy-line: "    const { data, error } = await supabase.rpc('mutate_pet_inventory_item', {"
// legacy-line: "      p_item_id: itemId,"
// legacy-line: "      p_delta: delta,"
// legacy-line: "    });"
// legacy-line: "    if (error) throw error;"
// legacy-line: "    return data as number;"
// legacy-line: "  },"
// legacy-line: ""
// legacy-line: "  async mutateCoins(userId: string, delta: number): Promise<number> {"
// legacy-line: "    // Atomic coin earn/spend (Phase"
// legacy-line: "    // SNABBB-SHARED-VIRTUAL-PET-COINS-CONCURRENCY-HARDENING) — a single"
// legacy-line: "    // `UPDATE ... SET coins = coins + delta` under Postgres's own row"
// legacy-line: "    // lock, the same pattern mutateInventoryItem uses for items. Fails"
// legacy-line: "    // (throws) rather than silently clamping when a spend would take"
// legacy-line: "    // the balance below 0. `auth.uid()` is derived server-side — this"
// legacy-line: "    // repository has no way to mutate another user's balance even if"
// legacy-line: "    // `userId` here were wrong."
// legacy-line: "    const { data, error } = await supabase.rpc('mutate_pet_coins', {"
// legacy-line: "      p_delta: delta,"
// legacy-line: "    });"
// legacy-line: "    if (error) throw error;"
// legacy-line: "    return data as number;"
// legacy-line: "  },"
// legacy-line: ""
// legacy-line: "  async purchasePetItem(userId: string, itemId: string, price: number): Promise<{ coins: number; quantity: number }> {"
// legacy-line: "    // One shop purchase as one transaction (Phase"
// legacy-line: "    // SNABBB-SHARED-VIRTUAL-PET-COINS-CONCURRENCY-HARDENING): validates"
// legacy-line: "    // affordability, deducts coins, and grants the item all inside"
// legacy-line: "    // public.purchase_pet_item, so a purchase can never leave coins"
// legacy-line: "    // deducted without the item (or vice versa), and two concurrent"
// legacy-line: "    // purchases can never both succeed against a balance that can only"
// legacy-line: "    // cover one of them."
// legacy-line: "    const { data, error } = await supabase.rpc('purchase_pet_item', {"
// legacy-line: "      p_item_id: itemId,"
// legacy-line: "      p_price: price,"
// legacy-line: "    });"
// legacy-line: "    if (error) throw error;"
// legacy-line: "    const row = Array.isArray(data) ? data[0] : data;"
// legacy-line: "    return { coins: row.out_coins, quantity: row.out_quantity };"
// legacy-line: "  },"
// legacy-line: ""
// legacy-line: "  async addXP(userId: string, delta: number): Promise<{ xp: number; level: number; levelsGained: number; coins: number }> {"
// legacy-line: "    // Server-authoritative atomic XP/level progression (Phase"
// legacy-line: "    // SNABBB-SHARED-VIRTUAL-PET-XP-LEVEL-CONCURRENCY-HARDENING):"
// legacy-line: "    // public.add_pet_xp locks this user's own inventory_pet row, adds"
// legacy-line: "    // `delta` to the CURRENT server-side xp, and determines the"
// legacy-line: "    // resulting xp/level/coin-reward from that current value under the"
// legacy-line: "    // same transaction -- never from a client-supplied final level,"
// legacy-line: "    // which could be computed from a stale local snapshot. The"
// legacy-line: "    // threshold/reward rule (100 XP per level, +50 coins per level,"
// legacy-line: "    // one check per call) is a deliberate exact port of the shared"
// legacy-line: "    // runtime's own client-side addXP."
// legacy-line: "    const { data, error } = await supabase.rpc('add_pet_xp', {"
// legacy-line: "      p_delta: delta,"
// legacy-line: "    });"
// legacy-line: "    if (error) throw error;"
// legacy-line: "    const row = Array.isArray(data) ? data[0] : data;"
// legacy-line: "    return { xp: row.out_xp, level: row.out_level, levelsGained: row.out_levels_gained, coins: row.out_coins };"
// legacy-line: "  },"
// legacy-line: ""
// legacy-line: "  async loadCatalog(): Promise<FoodItem[]> {"
// legacy-line: "    // `loadCatalog()` takes no parameters per the Shared `PetRepository`"
// legacy-line: "    // contract, so the authenticated user isn't handed to us — resolve a"
// legacy-line: "    // fresh canonical Supabase auth lookup here rather than reusing any"
// legacy-line: "    // captured component state, which could be stale across an account"
// legacy-line: "    // switch/reconciliation."
// legacy-line: "    const {"
// legacy-line: "      data: { user: authUser },"
// legacy-line: "    } = await supabase.auth.getUser();"
// legacy-line: "    const currentUserId = authUser?.id ?? null;"
// legacy-line: ""
// legacy-line: "    const columns = 'id, user_id, item_id, name, emoji, category_id, base_price_usd, hunger, happiness, hygiene, energy_gain, image_src, unlock_level';"
// legacy-line: "    // Narrow at the query itself to the two eligible scopes (global default"
// legacy-line: "    // + this user's own overrides) rather than fetching every user's rows"
// legacy-line: "    // and filtering client-side — another user's pricing override must"
// legacy-line: "    // never leave the DB for this request."
// legacy-line: "    const { data, error } = currentUserId"
// legacy-line: "      ? await supabase"
// legacy-line: "          .from('aiboard_pricing_items')"
// legacy-line: "          .select(columns)"
// legacy-line: "          .or(`user_id.is.null,user_id.eq.${currentUserId}`)"
// legacy-line: "          .order('unlock_level', { ascending: true })"
// legacy-line: "      : await supabase"
// legacy-line: "          .from('aiboard_pricing_items')"
// legacy-line: "          .select(columns)"
// legacy-line: "          .is('user_id', null)"
// legacy-line: "          .order('unlock_level', { ascending: true });"
// legacy-line: ""
// legacy-line: "    if (error || !data || data.length === 0) {"
// legacy-line: "      if (error) console.error('[appGalleryPetRepository] Failed to load aiboard_pricing_items:', error);"
// legacy-line: "      return [];"
// legacy-line: "    }"
// legacy-line: ""
// legacy-line: "    // Resolve exactly one effective row per canonical item_id: a"
// legacy-line: "    // user-specific override (user_id = current user) wins over the global"
// legacy-line: "    // default (user_id IS NULL), which is fallback-only. This is"
// legacy-line: "    // order-independent — it never assumes which scope the DB returns"
// legacy-line: "    // first — and defends against unexpected same-scope duplicates by"
// legacy-line: "    // keeping the first-seen row per scope and warning about the rest"
// legacy-line: "    // instead of silently picking one."
// legacy-line: "    const globalRows = new Map<string, PricingItemRow>();"
// legacy-line: "    const userRows = new Map<string, PricingItemRow>();"
// legacy-line: "    for (const row of data as PricingItemRow[]) {"
// legacy-line: "      const isGlobal = row.user_id === null;"
// legacy-line: "      const bucket = isGlobal ? globalRows : userRows;"
// legacy-line: "      const existing = bucket.get(row.item_id);"
// legacy-line: "      if (existing) {"
// legacy-line: "        console.warn('[appGalleryPetRepository] Duplicate catalog row within same scope for item_id — data-integrity anomaly, ignoring extra row:', {"
// legacy-line: "          item_id: row.item_id,"
// legacy-line: "          scope: isGlobal ? 'global' : 'user',"
// legacy-line: "          row_ids: [existing.id, row.id],"
// legacy-line: "        });"
// legacy-line: "        continue;"
// legacy-line: "      }"
// legacy-line: "      bucket.set(row.item_id, row);"
// legacy-line: "    }"
// legacy-line: ""
// legacy-line: "    const itemIds = new Set<string>([...globalRows.keys(), ...userRows.keys()]);"
// legacy-line: ""
// legacy-line: "    const items: FoodItem[] = [];"
// legacy-line: "    for (const itemId of itemIds) {"
// legacy-line: "      const userRow = userRows.get(itemId);"
// legacy-line: "      const globalRow = globalRows.get(itemId);"
// legacy-line: ""
// legacy-line: "      let effectiveRow = userRow ?? globalRow!;"
// legacy-line: "      let parsed = parseCatalogPrice(effectiveRow.base_price_usd);"
// legacy-line: ""
// legacy-line: "      // An invalid user-specific override does not get to hide a valid"
// legacy-line: "      // global default — fall back to it instead of dropping the item."
// legacy-line: "      if (!Number.isFinite(parsed) && userRow && globalRow) {"
// legacy-line: "        const globalParsed = parseCatalogPrice(globalRow.base_price_usd);"
// legacy-line: "        if (Number.isFinite(globalParsed)) {"
// legacy-line: "          effectiveRow = globalRow;"
// legacy-line: "          parsed = globalParsed;"
// legacy-line: "        }"
// legacy-line: "      }"
// legacy-line: ""
// legacy-line: "      if (!Number.isFinite(parsed)) {"
// legacy-line: "        console.warn('[appGalleryPetRepository] Skipping catalog row with invalid base_price_usd:', {"
// legacy-line: "          id: effectiveRow.id,"
// legacy-line: "          item_id: effectiveRow.item_id,"
// legacy-line: "          name: effectiveRow.name,"
// legacy-line: "        });"
// legacy-line: "        continue;"
// legacy-line: "      }"
// legacy-line: ""
// legacy-line: "      const row = effectiveRow;"
// legacy-line: "      items.push({"
// legacy-line: "        id: row.item_id,"
// legacy-line: "        icon: row.emoji || '🍽️',"
// legacy-line: "        label: row.name,"
// legacy-line: "        hunger: row.hunger ?? 10,"
// legacy-line: "        happiness: row.happiness ?? 0,"
// legacy-line: "        hygiene: row.hygiene ?? 0,"
// legacy-line: "        energyGain: row.energy_gain ?? 0,"
// legacy-line: "        imageSrc: row.image_src || undefined,"
// legacy-line: "        xp: Math.max(1, Math.round(Math.max(row.hunger ?? 0, row.happiness ?? 0, row.hygiene ?? 0, row.energy_gain ?? 0, 2) / 2)),"
// legacy-line: "        price: parsed,"
// legacy-line: "        category: row.category_id"
// legacy-line: "          ? row.category_id.charAt(0).toUpperCase() + row.category_id.slice(1)"
// legacy-line: "          : 'Other',"
// legacy-line: "        levelReq: row.unlock_level ?? 1,"
// legacy-line: "      });"
// legacy-line: "    }"
// legacy-line: "    return items;"
// legacy-line: "  },"
// legacy-line: ""
// legacy-line: "  async loadCurrencyRate(currencyCode: string): Promise<{ code: string; rate: number } | null> {"
// legacy-line: "    const { data, error } = await supabase"
// legacy-line: "      .from('aiboard_pricing_currencies')"
// legacy-line: "      .select('currency_code, rate')"
// legacy-line: "      .ilike('currency_code', currencyCode)"
// legacy-line: "      .maybeSingle();"
// legacy-line: ""
// legacy-line: "    if (error || !data) return null;"
// legacy-line: "    return { code: data.currency_code, rate: Number(data.rate) || 1 };"
// legacy-line: "  },"
// legacy-line: "};"
// legacy-line: ""
