// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "// PHASE 9B (Virtual Pet migration): thin host wrapper around"
// legacy-line: "// `@mrburdeveloperteam/pet-function/pet`'s <SharedVirtualPet>."
// legacy-line: "//"
// legacy-line: "// Everything generic (room UI, adoption UI, shop/inventory UI, stat"
// legacy-line: "// runtime/decay tick, XP/level/coin arithmetic, mini-game embedding shell,"
// legacy-line: "// landscape/fullscreen handling for paccat/tetris, body-scroll lock on"
// legacy-line: "// open/close) now lives in the shared package — confirmed byte-identical to"
// legacy-line: "// App Gallery's own pre-migration `VirtualPet/context/GameStateContext.tsx`"
// legacy-line: "// / `VirtualPet/constants.ts` / `VirtualPet/VirtualPetContainer.tsx` by"
// legacy-line: "// reading the installed `dist/pet.js` directly (same INITIAL_STATS,"
// legacy-line: "// XP_TO_LEVEL_UP, game asset paths)."
// legacy-line: "//"
// legacy-line: "// KNOWN, ACCEPTED BEHAVIOR ADDITION (manual-acceptance item): App Gallery's"
// legacy-line: "// own pre-migration `VirtualPetContainer.tsx`/`GamePage.tsx` had NO"
// legacy-line: "// landscape-orientation-lock or fullscreen-request logic at all for"
// legacy-line: "// paccat/tetris — confirmed by a fresh repo-wide grep before this file was"
// legacy-line: "// written. The shared runtime DOES own this behavior internally for those"
// legacy-line: "// two games. Adopting `SharedVirtualPet` therefore adds landscape/"
// legacy-line: "// fullscreen handling that did not exist before, rather than replacing an"
// legacy-line: "// equivalent host mechanism — this is a new, additive behavior, not a"
// legacy-line: "// silently-dropped one, and must be manually verified as acceptable."
// legacy-line: "//"
// legacy-line: "// What stays here, unchanged from the old `VirtualPet/VirtualPetContainer.tsx`,"
// legacy-line: "// is exactly what's genuinely App-Gallery-specific and Supabase-coupled:"
// legacy-line: "//   - IP geolocation + currency detection (`detectAndLogVisit`,"
// legacy-line: "//     `virtual_pet_visits` writes) — byte-identical to the pre-migration"
// legacy-line: "//     source, ported mechanically. Still resolves its own session"
// legacy-line: "//     independently — this is a one-off geo/currency log, not Pet"
// legacy-line: "//     ownership, and doesn't gate any persisted Pet state."
// legacy-line: "//"
// legacy-line: "// PHASE APPGALLERY-HOST-1: `userId` is now supplied by `App.tsx` as a"
// legacy-line: "// prop, sourced from `personalizedMatchedUserId` — the app's own"
// legacy-line: "// generation-guarded reconciliation between its primary Odoo/SSO identity"
// legacy-line: "// and Supabase Auth (see App.tsx's `reconcileSupabaseIdentity`), NOT an"
// legacy-line: "// independent `supabase.auth.getSession()` call made here. That"
// legacy-line: "// independent resolution used to guarantee a `userId = null` render on"
// legacy-line: "// every fresh mount before its own fetch settled, and never re-ran on a"
// legacy-line: "// direct account switch (its effect had an empty dependency array) —"
// legacy-line: "// leaving `SharedVirtualPet` operating under a stale previous user's id."
// legacy-line: "// Live RLS policies on `inventory_pet`/`pet_inventory`/`virtual_pet_visits`"
// legacy-line: "// (`auth.uid() = user_id`) confirm the backend expects exactly the raw"
// legacy-line: "// current Supabase session's own id, which is exactly what"
// legacy-line: "// `personalizedMatchedUserId` resolves to once reconciliation confirms a"
// legacy-line: "// match — never email, never an Odoo-only identifier."
// legacy-line: "//"
// legacy-line: "// GLOBAL PET BACKEND FREEZE: `userId` below is App Gallery's own"
// legacy-line: "// Supabase-auth-session id — the same opaque value the pre-migration Pet"
// legacy-line: "// code already used. It is passed into `SharedVirtualPet`'s `userId` prop"
// legacy-line: "// (which the shared contract internally labels `globalUserId` purely as a"
// legacy-line: "// forward-looking parameter name — see `PetSaveSnapshot.globalUserId`'s"
// legacy-line: "// own doc in the installed package). No cross-app identity resolution,"
// legacy-line: "// mapping, or merge is introduced by this phase."
// legacy-line: "//"
// legacy-line: "// The old `VirtualPetContainer.tsx` also toggled"
// legacy-line: "// `document.body.style.overflow` ('hidden'/'auto') on open/close — dropped"
// legacy-line: "// here since `SharedVirtualPet` already performs the exact same toggle"
// legacy-line: "// internally (confirmed by reading `dist/pet.js`); keeping it host-side"
// legacy-line: "// too would just be a redundant second write to the same style property,"
// legacy-line: "// not a behavior difference."
// legacy-line: "import { useEffect, useRef, useState } from 'react';"
// legacy-line: "import { SharedVirtualPet } from '@mrburdeveloperteam/pet-function/pet';"
// legacy-line: "import type { ExtraGame } from '@mrburdeveloperteam/pet-function/pet';"
// legacy-line: "import { supabase } from '../services/supabaseClient';"
// legacy-line: "import { appGalleryPetRepository } from './appGalleryPetRepository';"
// legacy-line: "import { PET_ASSET_URLS } from '../aiExperience/molarExperienceAssets';"
// legacy-line: ""
// legacy-line: "interface GeoInfo {"
// legacy-line: "  ip: string;"
// legacy-line: "  country_name: string;"
// legacy-line: "  country_code: string;"
// legacy-line: "  city: string;"
// legacy-line: "  region: string;"
// legacy-line: "  timezone: string;"
// legacy-line: "  currency: string; // e.g. \"MYR\", \"USD\", \"EUR\""
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "const DEFAULT_CURRENCY_CODE = 'USD';"
// legacy-line: ""
// legacy-line: "const normalizeCurrencyCode = (currency?: string | null) => {"
// legacy-line: "  const normalized = (currency || '').trim().toUpperCase();"
// legacy-line: "  return /^[A-Z]{3}$/.test(normalized) ? normalized : DEFAULT_CURRENCY_CODE;"
// legacy-line: "};"
// legacy-line: ""
// legacy-line: "const getSupportedPricingCurrency = async (currency?: string | null): Promise<string> => {"
// legacy-line: "  const requestedCurrency = normalizeCurrencyCode(currency);"
// legacy-line: "  if (requestedCurrency === DEFAULT_CURRENCY_CODE) return DEFAULT_CURRENCY_CODE;"
// legacy-line: ""
// legacy-line: "  try {"
// legacy-line: "    const { data, error } = await supabase"
// legacy-line: "      .from('aiboard_pricing_currencies')"
// legacy-line: "      .select('currency_code')"
// legacy-line: "      .ilike('currency_code', requestedCurrency)"
// legacy-line: "      .maybeSingle();"
// legacy-line: ""
// legacy-line: "    if (!error && data?.currency_code) {"
// legacy-line: "      return normalizeCurrencyCode(data.currency_code);"
// legacy-line: "    }"
// legacy-line: "  } catch (err) {"
// legacy-line: "    console.warn('[Currency] Failed to verify pricing currency:', err);"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  console.warn(`[Currency] ${requestedCurrency} is not configured in aiboard_pricing_currencies. Using USD.`);"
// legacy-line: "  return DEFAULT_CURRENCY_CODE;"
// legacy-line: "};"
// legacy-line: ""
// legacy-line: "// Detect IP/country and log the visit to Supabase"
// legacy-line: "// Fallback chain: ipapi.co → last stored visit currency → 'USD'"
// legacy-line: "async function detectAndLogVisit(): Promise<string> {"
// legacy-line: "  // --- Attempt 1: Live geolocation ---"
// legacy-line: "  try {"
// legacy-line: "    const res = await fetch('https://ipapi.co/json/');"
// legacy-line: "    if (res.ok) {"
// legacy-line: "      const geo: GeoInfo = await res.json();"
// legacy-line: ""
// legacy-line: "      const { data: sessionData } = await supabase.auth.getSession();"
// legacy-line: "      const userId = sessionData?.session?.user?.id ?? null;"
// legacy-line: ""
// legacy-line: "      if (userId) {"
// legacy-line: "        const { error: visitError } = await supabase.from('virtual_pet_visits').upsert("
// legacy-line: "          {"
// legacy-line: "            user_id: userId,"
// legacy-line: "            ip: geo.ip,"
// legacy-line: "            country: geo.country_name,"
// legacy-line: "            country_code: geo.country_code,"
// legacy-line: "            city: geo.city,"
// legacy-line: "            region: geo.region,"
// legacy-line: "            timezone: geo.timezone,"
// legacy-line: "            currency: normalizeCurrencyCode(geo.currency),"
// legacy-line: "            visited_at: new Date().toISOString(),"
// legacy-line: "          },"
// legacy-line: "          { onConflict: 'user_id' }"
// legacy-line: "        );"
// legacy-line: ""
// legacy-line: "        if (visitError) {"
// legacy-line: "          console.warn('[VirtualPet] Could not save visit location:', visitError.message);"
// legacy-line: "        }"
// legacy-line: "      }"
// legacy-line: ""
// legacy-line: "      console.log(`[VirtualPet] Visit logged — ${geo.city}, ${geo.country_name} (${geo.currency})`);"
// legacy-line: "      return getSupportedPricingCurrency(geo.currency);"
// legacy-line: "    }"
// legacy-line: "  } catch {"
// legacy-line: "    console.warn('[VirtualPet] Geolocation failed, trying stored record...');"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  // --- Attempt 2: Use last known currency from Supabase ---"
// legacy-line: "  try {"
// legacy-line: "    const { data: sessionData } = await supabase.auth.getSession();"
// legacy-line: "    const userId = sessionData?.session?.user?.id ?? null;"
// legacy-line: ""
// legacy-line: "    if (userId) {"
// legacy-line: "      const { data: lastVisit } = await supabase"
// legacy-line: "        .from('virtual_pet_visits')"
// legacy-line: "        .select('currency')"
// legacy-line: "        .eq('user_id', userId)"
// legacy-line: "        .not('currency', 'is', null)"
// legacy-line: "        .order('visited_at', { ascending: false })"
// legacy-line: "        .limit(1)"
// legacy-line: "        .maybeSingle();"
// legacy-line: ""
// legacy-line: "      if (lastVisit?.currency) {"
// legacy-line: "        console.log(`[VirtualPet] Using stored currency: ${lastVisit.currency}`);"
// legacy-line: "        return getSupportedPricingCurrency(lastVisit.currency);"
// legacy-line: "      }"
// legacy-line: "    }"
// legacy-line: "  } catch {"
// legacy-line: "    console.warn('[VirtualPet] Could not fetch stored visit currency.');"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  // --- Fallback: USD ---"
// legacy-line: "  return DEFAULT_CURRENCY_CODE;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "interface AppGalleryVirtualPetProps {"
// legacy-line: "  isOpen: boolean;"
// legacy-line: "  onClose: () => void;"
// legacy-line: "  /** App Gallery's own reconciled Supabase auth id"
// legacy-line: "   *  (`personalizedMatchedUserId`) — `null` for true guest/unreconciled."
// legacy-line: "   *  See this file's header for why no additional auth lookup happens"
// legacy-line: "   *  here. */"
// legacy-line: "  userId: string | null;"
// legacy-line: "  /** Meowdoku, already live in Production via the legacy VirtualPet room"
// legacy-line: "   *  (`VirtualPet/components/RoomMenus.tsx`/`GamePage.tsx`), rendered here"
// legacy-line: "   *  as a 4th game card via the shared package's `extraGames` slot instead"
// legacy-line: "   *  of being ported into the shared runtime itself — this package never"
// legacy-line: "   *  opens or persists state for these, only calls `onSelect`. */"
// legacy-line: "  extraGames?: ExtraGame[];"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export default function AppGalleryVirtualPet({ isOpen, onClose, userId, extraGames }: AppGalleryVirtualPetProps) {"
// legacy-line: "  const hasLoggedRef = useRef(false);"
// legacy-line: "  const [detectedCurrency, setDetectedCurrency] = useState(DEFAULT_CURRENCY_CODE);"
// legacy-line: ""
// legacy-line: "  useEffect(() => {"
// legacy-line: "    if (isOpen) {"
// legacy-line: "      // Detect geo only once per open session"
// legacy-line: "      if (!hasLoggedRef.current) {"
// legacy-line: "        hasLoggedRef.current = true;"
// legacy-line: "        detectAndLogVisit().then((currency) => {"
// legacy-line: "          setDetectedCurrency(currency);"
// legacy-line: "        });"
// legacy-line: "      }"
// legacy-line: "    } else {"
// legacy-line: "      hasLoggedRef.current = false; // Reset so next open logs again"
// legacy-line: "    }"
// legacy-line: "  }, [isOpen]);"
// legacy-line: ""
// legacy-line: "  return ("
// legacy-line: "    <SharedVirtualPet"
// legacy-line: "      isOpen={isOpen}"
// legacy-line: "      onClose={onClose}"
// legacy-line: "      repository={appGalleryPetRepository}"
// legacy-line: "      userId={userId}"
// legacy-line: "      currencyCode={detectedCurrency}"
// legacy-line: "      assetUrls={PET_ASSET_URLS}"
// legacy-line: "      extraGames={extraGames}"
// legacy-line: "    />"
// legacy-line: "  );"
// legacy-line: "}"
// legacy-line: ""
