// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "// Snabbb AI Experience — Phase 1 canonical candidate contract."
// legacy-line: "//"
// legacy-line: "// This is the ONE deterministic candidate/fact shape intended to eventually"
// legacy-line: "// feed three surfaces without duplicating business logic:"
// legacy-line: "//   1. Cat Dialogue (the only active consumer today — see features/petDialogue)"
// legacy-line: "//   2. Mini-App Landing Insight (not implemented in Phase 1)"
// legacy-line: "//   3. Data-Driven Chat grounding context (not implemented in Phase 1)"
// legacy-line: "//"
// legacy-line: "// The one architectural requirement Phase 1 exists to satisfy: FACTS"
// legacy-line: "// (structured, machine-readable) must be separate from the RENDERED MESSAGE"
// legacy-line: "// (the exact string already shown to the user). `facts` + `messageTemplate`"
// legacy-line: "// are the new, additive fields that make that separation real; `message`"
// legacy-line: "// remains the byte-for-byte identical rendered string every provider already"
// legacy-line: "// produced before this refactor."
// legacy-line: "//"
// legacy-line: "// Design choice — additive, not a rewrite: every field the pre-Phase-1"
// legacy-line: "// `DialogueCandidate` type had (userState, dialogueId, priority, message,"
// legacy-line: "// action, source, dedupeKey, ruleVersion, bypassEntryWalk, autoCloseMs,"
// legacy-line: "// eventTime, createdTime, recordId) is preserved verbatim below under a"
// legacy-line: "// \"legacy-compatible\" heading. `features/petDialogue/types.ts`'s"
// legacy-line: "// `DialogueCandidate` is now a direct alias of `InsightCandidate` — every"
// legacy-line: "// existing consumer (resolveDialogue.ts, usePersonalizedPetDialogue.ts,"
// legacy-line: "// CatMascot.tsx) keeps compiling and behaving identically without any"
// legacy-line: "// changes on their end. Only the providers that BUILD candidates were"
// legacy-line: "// touched, to additionally populate the new canonical fields."
// legacy-line: "//"
// legacy-line: "// Two fields are intentionally duplicated with their legacy equivalent"
// legacy-line: "// rather than replacing them, exactly per the allowance for temporary"
// legacy-line: "// backward-compatible duplication:"
// legacy-line: "//   - `sourceRecordId` (canonical) mirrors `recordId`/`source.recordId`"
// legacy-line: "//     (legacy) — the legacy fields stay because resolveDialogue.ts's"
// legacy-line: "//     tie-break reads `recordId` directly and must not be touched."
// legacy-line: "//   - `evaluatedAt` (canonical, top-level) mirrors `source.evaluatedAt`"
// legacy-line: "//     (legacy) — both are set from the same single `new Date().toISOString()`"
// legacy-line: "//     call per candidate build, so they can never drift apart."
// legacy-line: "// `app` (canonical) is also deliberately distinct from `source.app` (legacy)"
// legacy-line: "// for two candidates where the underlying data-source label and the"
// legacy-line: "// mini-app category differ on purpose — see InsightApp below."
// legacy-line: ""
// legacy-line: "import type {"
// legacy-line: "  DialogueAction,"
// legacy-line: "  DialogueId,"
// legacy-line: "  DialoguePriority,"
// legacy-line: "  DialogueSource,"
// legacy-line: "  DialogueUserState,"
// legacy-line: "} from '@/features/petDialogue/types';"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Canonical mini-app / surface category a candidate conceptually belongs"
// legacy-line: " * to — this is what a future Mini-App Landing Insight surface would key"
// legacy-line: " * off of, not the literal Supabase/service origin (`source.app`, unchanged"
// legacy-line: " * legacy field). `legacy` and `system` are deliberate: the Post-Login Intro"
// legacy-line: " * and Welcome Fallback candidates don't belong to any one mini-app, and"
// legacy-line: " * forcing them into `inventory`/`todo`/`appointments`/`profile` would be"
// legacy-line: " * inaccurate — see legacyIntroProvider.ts (`source.app: 'aiboard'`) and the"
// legacy-line: " * fallback builder (`source.app: 'gallery'`), both preserved unchanged."
// legacy-line: " */"
// legacy-line: "export type InsightApp = 'inventory' | 'todo' | 'appointments' | 'profile' | 'legacy' | 'system';"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Canonical trigger identity. Reuses the existing petDialogue `DialogueId`"
// legacy-line: " * string values verbatim (`expired_inventory`, `overdue_high_task`, ...) —"
// legacy-line: " * Phase 1 introduces no new or duplicate trigger identities; `triggerId`"
// legacy-line: " * and the legacy `dialogueId` field always hold the exact same string for"
// legacy-line: " * any given candidate."
// legacy-line: " */"
// legacy-line: "export type InsightTriggerId = DialogueId;"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * The canonical Phase 1 candidate contract. Generic over `TFacts` so each"
// legacy-line: " * provider can declare its own structured fact shape (see"
// legacy-line: " * features/petDialogue/providers/*.ts) while every consumer that only needs"
// legacy-line: " * the legacy-compatible fields (ranking, dedupe, rendering) can keep"
// legacy-line: " * treating this as `InsightCandidate` with an unconstrained `facts` object —"
// legacy-line: " * exactly what `DialogueCandidate` in petDialogue/types.ts now is."
// legacy-line: " */"
// legacy-line: "export interface InsightCandidate<TFacts = unknown> {"
// legacy-line: "  // ---- Canonical Phase 1 fields ----------------------------------------"
// legacy-line: "  /** Mini-app / surface category — see InsightApp. */"
// legacy-line: "  app: InsightApp;"
// legacy-line: "  /** Canonical trigger identity — always equal to `dialogueId` below. */"
// legacy-line: "  triggerId: InsightTriggerId;"
// legacy-line: "  /** Structured facts the deterministic rule actually used to decide this"
// legacy-line: "   *  candidate exists — the one thing a future grounded-chat/landing-insight"
// legacy-line: "   *  surface can read without re-querying or reverse-parsing `message`. */"
// legacy-line: "  facts: TFacts;"
// legacy-line: "  /** Deterministic, approved canonical template (with `{placeholder}`"
// legacy-line: "   *  tokens where the rendered message varies) — distinct from `message`,"
// legacy-line: "   *  the already-rendered string. No AI ever rewrites either field in"
// legacy-line: "   *  Phase 1. */"
// legacy-line: "  messageTemplate: string;"
// legacy-line: "  /** Canonical mirror of `recordId`/`source.recordId` — `null` when a"
// legacy-line: "   *  candidate has no real database record (none currently do, but the"
// legacy-line: "   *  contract must not force a fabricated id if a future provider has"
// legacy-line: "   *  none). */"
// legacy-line: "  sourceRecordId: string | null;"
// legacy-line: "  /** Canonical mirror of `source.evaluatedAt`, from the same timestamp. */"
// legacy-line: "  evaluatedAt: string;"
// legacy-line: ""
// legacy-line: "  // ---- Legacy-compatible fields (unchanged; every existing consumer"
// legacy-line: "  // reads these exactly as before Phase 1) -------------------------------"
// legacy-line: "  userState: DialogueUserState;"
// legacy-line: "  dialogueId: InsightTriggerId;"
// legacy-line: "  priority: DialoguePriority;"
// legacy-line: "  message: string;"
// legacy-line: "  action?: DialogueAction;"
// legacy-line: "  source: DialogueSource;"
// legacy-line: "  expiresAt?: string;"
// legacy-line: "  dedupeKey: string;"
// legacy-line: "  ruleVersion: string;"
// legacy-line: "  /** P0 alerts may bypass the cosmetic entry-walk gate; everything else waits for it. */"
// legacy-line: "  bypassEntryWalk?: boolean;"
// legacy-line: "  /** Only the fixed welcome fallback uses this today. */"
// legacy-line: "  autoCloseMs?: number;"
// legacy-line: "  /** Event/condition time (e.g. an expiry date) — first tie-breaker within the same priority. */"
// legacy-line: "  eventTime?: string;"
// legacy-line: "  /** Record creation time — second tie-breaker within the same priority. */"
// legacy-line: "  createdTime?: string;"
// legacy-line: "  /** Stable record id — final tie-breaker. Callers fall back to dedupeKey when no natural id exists. */"
// legacy-line: "  recordId?: string;"
// legacy-line: "}"
// legacy-line: ""
