// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "// Strict clinic-device-local date/time construction for the Appointment"
// legacy-line: "// Within 2 Hours dialogue. `public.appointments` stores `date` (a plain"
// legacy-line: "// Postgres `date`) and `start_time` (free-text, confirmed live to always be"
// legacy-line: "// zero-padded 24-hour `HH:mm`, written by the Appointment app's own"
// legacy-line: "// `addMinutes`/slot-generation helpers — see appointment repo"
// legacy-line: "// `src/utils/time.js`) with no timezone column anywhere. Per the approved"
// legacy-line: "// Phase decision, both are interpreted as clinic-device-local wall-clock"
// legacy-line: "// time — never UTC, never `Date.parse`, never a timezone inferred from"
// legacy-line: "// anywhere else."
// legacy-line: ""
// legacy-line: "import { toValidatedDateKey } from './dateUtils';"
// legacy-line: ""
// legacy-line: "// `HH:mm` is the only format confirmed live and at the Appointment write"
// legacy-line: "// path; `HH:mm:ss` is additionally accepted since it's a strict superset"
// legacy-line: "// the same regex can validate for free, per the task's explicit allowance."
// legacy-line: "// No 12-hour AM/PM parsing — not used anywhere in the write path."
// legacy-line: "const TIME_PATTERN = /^(\\d{2}):(\\d{2})(?::(\\d{2}))?$/;"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Validates and constructs a clinic-device-local `Date` from a raw"
// legacy-line: " * `appointments.date` + `appointments.start_time` pair, or returns `null`"
// legacy-line: " * if either input is missing, malformed, or describes an impossible"
// legacy-line: " * calendar date/time (e.g. `2026-02-30`, hour `24`). Never throws — every"
// legacy-line: " * input is type/shape-checked before use, so one malformed appointment row"
// legacy-line: " * can be skipped by the caller rather than failing the whole evaluation."
// legacy-line: " *"
// legacy-line: " * Deliberately does not use `Date.parse`, `new Date(\\`${date}T${time}Z\\`)`,"
// legacy-line: " * or any UTC-based construction: `new Date(year, month - 1, day, hour,"
// legacy-line: " * minute, second, 0)` is the local-time constructor, and every resulting"
// legacy-line: " * field is re-read and compared against the input to catch JavaScript's"
// legacy-line: " * silent rollover (e.g. hour 24 would otherwise roll into the next day)."
// legacy-line: " */"
// legacy-line: "export function buildClinicDeviceLocalAppointmentStart(date: unknown, startTime: unknown): Date | null {"
// legacy-line: "  if (typeof date !== 'string' || typeof startTime !== 'string') return null;"
// legacy-line: ""
// legacy-line: "  const validatedDateKey = toValidatedDateKey(date);"
// legacy-line: "  if (!validatedDateKey) return null;"
// legacy-line: ""
// legacy-line: "  const match = TIME_PATTERN.exec(startTime.trim());"
// legacy-line: "  if (!match) return null;"
// legacy-line: ""
// legacy-line: "  const hour = Number(match[1]);"
// legacy-line: "  const minute = Number(match[2]);"
// legacy-line: "  const second = match[3] !== undefined ? Number(match[3]) : 0;"
// legacy-line: ""
// legacy-line: "  if (!Number.isInteger(hour) || hour < 0 || hour > 23) return null;"
// legacy-line: "  if (!Number.isInteger(minute) || minute < 0 || minute > 59) return null;"
// legacy-line: "  if (!Number.isInteger(second) || second < 0 || second > 59) return null;"
// legacy-line: ""
// legacy-line: "  const [year, month, day] = validatedDateKey.split('-').map(Number);"
// legacy-line: "  const start = new Date(year, month - 1, day, hour, minute, second, 0);"
// legacy-line: ""
// legacy-line: "  const rolledOver ="
// legacy-line: "    start.getFullYear() !== year ||"
// legacy-line: "    start.getMonth() !== month - 1 ||"
// legacy-line: "    start.getDate() !== day ||"
// legacy-line: "    start.getHours() !== hour ||"
// legacy-line: "    start.getMinutes() !== minute ||"
// legacy-line: "    start.getSeconds() !== second;"
// legacy-line: "  if (rolledOver) return null;"
// legacy-line: ""
// legacy-line: "  return start;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/** Zero-padded `HH:mm:ss` derived from an already-validated local `Date` —"
// legacy-line: " *  used only to build a canonical dedupe-key component, so `HH:mm` and"
// legacy-line: " *  `HH:mm:ss` source rows that describe the same instant produce the same"
// legacy-line: " *  key. Never used for display (see the `Intl.DateTimeFormat` call at the"
// legacy-line: " *  candidate-building call site for that). */"
// legacy-line: "export function toCanonicalLocalStartTime(start: Date): string {"
// legacy-line: "  const hh = String(start.getHours()).padStart(2, '0');"
// legacy-line: "  const mm = String(start.getMinutes()).padStart(2, '0');"
// legacy-line: "  const ss = String(start.getSeconds()).padStart(2, '0');"
// legacy-line: "  return `${hh}:${mm}:${ss}`;"
// legacy-line: "}"
// legacy-line: ""
