// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "// Centralized date handling for Phase 1A. The Inventory `expiry_date` column"
// legacy-line: "// is a plain Postgres `date` (no time-of-day, no timezone), so comparisons"
// legacy-line: "// here are calendar-date-only by design — not a substitute for real"
// legacy-line: "// timestamp/timezone handling, which is explicitly out of scope until"
// legacy-line: "// appointment/task triggers (P1/P2) are implemented."
// legacy-line: ""
// legacy-line: "export function toCalendarDateKey(date: Date): string {"
// legacy-line: "  const y = date.getFullYear();"
// legacy-line: "  const m = String(date.getMonth() + 1).padStart(2, '0');"
// legacy-line: "  const d = String(date.getDate()).padStart(2, '0');"
// legacy-line: "  return `${y}-${m}-${d}`;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "const DATE_KEY_PATTERN = /^\\d{4}-\\d{2}-\\d{2}$/;"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Parses a YYYY-MM-DD key into calendar-validated [year, month, day], or"
// legacy-line: " * `null` if the string isn't shaped like a date OR doesn't correspond to a"
// legacy-line: " * real calendar day (e.g. \"2024-02-30\", \"2024-13-01\"). The JS `Date`"
// legacy-line: " * constructor silently rolls invalid day/month values over into a"
// legacy-line: " * different, technically-valid date instead of rejecting them (`new"
// legacy-line: " * Date(2024, 1, 30)` becomes March 1) — re-reading the constructed date's"
// legacy-line: " * fields and comparing them against the input is what actually catches"
// legacy-line: " * that roll-over, so a malformed database value can never silently"
// legacy-line: " * masquerade as a real, comparable date and produce a P0/P1 candidate."
// legacy-line: " */"
// legacy-line: "function parseDateKeyParts(dateKey: string): [number, number, number] | null {"
// legacy-line: "  if (!DATE_KEY_PATTERN.test(dateKey)) return null;"
// legacy-line: "  const [y, m, d] = dateKey.split('-').map(Number);"
// legacy-line: "  if (m < 1 || m > 12 || d < 1 || d > 31) return null;"
// legacy-line: "  const date = new Date(y, m - 1, d);"
// legacy-line: "  if (date.getFullYear() !== y || date.getMonth() !== m - 1 || date.getDate() !== d) return null;"
// legacy-line: "  return [y, m, d];"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/** Normalizes and calendar-validates a raw date-ish value (e.g. a"
// legacy-line: " *  possibly-timestamp `expiry_date`/`date` column) down to a trustworthy"
// legacy-line: " *  YYYY-MM-DD key, or `null` if it isn't a real calendar date. Guards on"
// legacy-line: " *  `typeof !== 'string'` rather than mere truthiness: a non-string,"
// legacy-line: " *  non-falsy runtime value (defensive against a malformed row from a"
// legacy-line: " *  loosely-typed Supabase response) would otherwise reach `.slice()` and"
// legacy-line: " *  throw, which is never acceptable for a value this function's callers"
// legacy-line: " *  treat as \"just reject it and skip this one row.\" */"
// legacy-line: "export function toValidatedDateKey(rawDate: string | null | undefined): string | null {"
// legacy-line: "  if (typeof rawDate !== 'string') return null;"
// legacy-line: "  const normalized = rawDate.slice(0, 10);"
// legacy-line: "  return parseDateKeyParts(normalized) ? normalized : null;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * True only when `expiryDate` is strictly before today's calendar date. An"
// legacy-line: " * item expiring today is not yet treated as expired. Compares normalized,"
// legacy-line: " * calendar-validated YYYY-MM-DD keys, never locale-formatted strings — a"
// legacy-line: " * malformed or impossible date (e.g. \"2024-02-30\") is never treated as"
// legacy-line: " * expired, it's rejected outright."
// legacy-line: " */"
// legacy-line: "export function isExpiredBeforeToday(expiryDate: string | null | undefined, now: Date = new Date()): boolean {"
// legacy-line: "  const validated = toValidatedDateKey(expiryDate);"
// legacy-line: "  if (!validated) return false;"
// legacy-line: "  return validated < toCalendarDateKey(now);"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Adds `days` calendar days to a YYYY-MM-DD key, staying entirely in local"
// legacy-line: " * calendar-field arithmetic (parse → local Date at midnight → `setDate` →"
// legacy-line: " * re-read local fields) so month/year rollovers are handled correctly"
// legacy-line: " * without ever round-tripping through a UTC-interpreted ISO string."
// legacy-line: " */"
// legacy-line: "export function addCalendarDaysToDateKey(dateKey: string, days: number): string {"
// legacy-line: "  const parts = parseDateKeyParts(dateKey);"
// legacy-line: "  if (!parts) return dateKey;"
// legacy-line: "  const [y, m, d] = parts;"
// legacy-line: "  const date = new Date(y, m - 1, d);"
// legacy-line: "  date.setDate(date.getDate() + days);"
// legacy-line: "  return toCalendarDateKey(date);"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Deterministic integer calendar-day difference between two YYYY-MM-DD keys"
// legacy-line: " * (toDateKey - fromDateKey). Uses Date.UTC on the parsed y/m/d components"
// legacy-line: " * purely as a day-counting mechanism — never converts either key back to a"
// legacy-line: " * local wall-clock time — so it's immune to daylight-saving shifts."
// legacy-line: " */"
// legacy-line: "export function daysBetweenDateKeys(fromDateKey: string, toDateKey: string): number {"
// legacy-line: "  const from = parseDateKeyParts(fromDateKey);"
// legacy-line: "  const to = parseDateKeyParts(toDateKey);"
// legacy-line: "  if (!from || !to) return 0;"
// legacy-line: "  const fromUtcMs = Date.UTC(from[0], from[1] - 1, from[2]);"
// legacy-line: "  const toUtcMs = Date.UTC(to[0], to[1] - 1, to[2]);"
// legacy-line: "  return Math.round((toUtcMs - fromUtcMs) / 86_400_000);"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * True when `dateKey` falls within [startKey, endKey] inclusive. Pure"
// legacy-line: " * string comparison of normalized, calendar-validated YYYY-MM-DD keys —"
// legacy-line: " * never locale-formatted, never Date.parse. A malformed or impossible date"
// legacy-line: " * is rejected outright rather than being compared lexicographically (which"
// legacy-line: " * could otherwise place e.g. \"2024-02-30\" inside a window it doesn't really"
// legacy-line: " * belong in)."
// legacy-line: " */"
// legacy-line: "export function isWithinInclusiveDateWindow("
// legacy-line: "  dateKey: string | null | undefined,"
// legacy-line: "  startKey: string,"
// legacy-line: "  endKey: string"
// legacy-line: "): boolean {"
// legacy-line: "  const validated = toValidatedDateKey(dateKey);"
// legacy-line: "  if (!validated) return false;"
// legacy-line: "  return validated >= startKey && validated <= endKey;"
// legacy-line: "}"
// legacy-line: ""
