// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "// Single place to resolve the destinations Phase 1A action buttons can point"
// legacy-line: "// to, so the route strings aren't duplicated between providers and so"
// legacy-line: "// navigation always goes through a small, known set of destinations."
// legacy-line: "import { MINI_APPS } from '@/constants';"
// legacy-line: ""
// legacy-line: "const FALLBACK_INVENTORY_ROUTE = 'https://inventory.snabbb.com/';"
// legacy-line: "const FALLBACK_TODO_ROUTE = 'https://todo.snabbb.com/';"
// legacy-line: "const FALLBACK_APPOINTMENT_ROUTE = 'https://appointment.snabbb.com/';"
// legacy-line: "const PROFILE_SETTINGS_ROUTE = '/profile-settings';"
// legacy-line: ""
// legacy-line: "export function getInventoryAppRoute(): string {"
// legacy-line: "  const app = MINI_APPS.find((a) => a.title === 'Inventory');"
// legacy-line: "  return app?.route || FALLBACK_INVENTORY_ROUTE;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/** The Todo app's landing page only — never a task-detail path, which"
// legacy-line: " *  doesn't exist as a controlled destination. */"
// legacy-line: "export function getTodoAppRoute(): string {"
// legacy-line: "  const app = MINI_APPS.find((a) => a.title === 'To-Do Manager');"
// legacy-line: "  return app?.route || FALLBACK_TODO_ROUTE;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/** The Appointment app's landing page only — no appointment-detail route"
// legacy-line: " *  exists as a controlled destination. */"
// legacy-line: "export function getAppointmentAppRoute(): string {"
// legacy-line: "  const app = MINI_APPS.find((a) => a.title === 'Appointment');"
// legacy-line: "  return app?.route || FALLBACK_APPOINTMENT_ROUTE;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export function getProfileSettingsRoute(): string {"
// legacy-line: "  return PROFILE_SETTINGS_ROUTE;"
// legacy-line: "}"
// legacy-line: ""
