// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "// Shared, safe name-sanitization logic. Extracted from the existing Welcome"
// legacy-line: "// Back `[name]` interpolation in CatMascot so both the legacy DB-configured"
// legacy-line: "// path and the new Phase 1A fixed fallback resolve names identically and"
// legacy-line: "// never show a raw email address."
// legacy-line: ""
// legacy-line: "export interface DisplayNameSources {"
// legacy-line: "  profileName?: string | null;"
// legacy-line: "  profileFullName?: string | null;"
// legacy-line: "  metaName?: string | null;"
// legacy-line: "  email?: string | null;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export function resolveSafeDisplayName(input: DisplayNameSources): string | null {"
// legacy-line: "  let displayName: string | null = input.profileName || input.profileFullName || null;"
// legacy-line: "  if (!displayName) displayName = input.metaName || null;"
// legacy-line: "  if (!displayName && input.email) displayName = input.email.split('@')[0];"
// legacy-line: "  // Never show a raw email address, even if it came from profiles.name/full_name."
// legacy-line: "  if (displayName && displayName.includes('@')) displayName = displayName.split('@')[0];"
// legacy-line: "  return displayName;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export function resolveSafeFirstName(input: DisplayNameSources): string | null {"
// legacy-line: "  const full = resolveSafeDisplayName(input);"
// legacy-line: "  if (!full) return null;"
// legacy-line: "  const first = full.trim().split(/\\s+/)[0];"
// legacy-line: "  return first || null;"
// legacy-line: "}"
// legacy-line: ""
