// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "// Conservative task-title sanitizer for the Todo P0/P2 dialogue bubbles."
// legacy-line: "// A task title is user-authored free text, not a curated display string —"
// legacy-line: "// unlike an inventory item name, it's shown here for the first time without"
// legacy-line: "// any prior moderation. This never rewrites or infers meaning from the"
// legacy-line: "// title, it only strips formatting hazards and refuses anything too long or"
// legacy-line: "// empty, falling back to a generic message in that case."
// legacy-line: ""
// legacy-line: "const MAX_SAFE_TASK_TITLE_LENGTH = 80;"
// legacy-line: ""
// legacy-line: "// C0/C1 control characters (excluding the whitespace ones already handled"
// legacy-line: "// by the \\s+ collapse below) and zero-width formatting characters — none of"
// legacy-line: "// these render as anything useful in a compact bubble, and a zero-width"
// legacy-line: "// character in particular could otherwise be used to visually hide content"
// legacy-line: "// inside an apparently-short title. Built from a plain-ASCII \\u-escape"
// legacy-line: "// string via the RegExp constructor (rather than a literal regex character"
// legacy-line: "// class) so no actual control/zero-width byte is ever present in this"
// legacy-line: "// source file."
// legacy-line: "const UNSAFE_CONTROL_AND_ZERO_WIDTH_PATTERN = new RegExp("
// legacy-line: "  '[\\\\u0000-\\\\u0008\\\\u000B\\\\u000C\\\\u000E-\\\\u001F\\\\u007F\\\\u200B-\\\\u200D\\\\uFEFF]',"
// legacy-line: "  'g'"
// legacy-line: ");"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Returns a trimmed, single-line, length-capped title safe for the compact"
// legacy-line: " * mascot bubble, or `null` if the input isn't usable (blank, non-string, or"
// legacy-line: " * left empty after sanitization) - callers must fall back to a generic"
// legacy-line: " * message rather than rendering an empty quote."
// legacy-line: " */"
// legacy-line: "export function sanitizeTaskTitleForDialogue(rawTitle: unknown): string | null {"
// legacy-line: "  if (typeof rawTitle !== 'string') return null;"
// legacy-line: ""
// legacy-line: "  const withoutUnsafeChars = rawTitle.replace(UNSAFE_CONTROL_AND_ZERO_WIDTH_PATTERN, '');"
// legacy-line: "  const singleLine = withoutUnsafeChars.replace(/[\\r\\n]+/g, ' ');"
// legacy-line: "  const collapsedWhitespace = singleLine.replace(/\\s+/g, ' ').trim();"
// legacy-line: "  if (collapsedWhitespace.length === 0) return null;"
// legacy-line: ""
// legacy-line: "  // Truncate by Unicode code point, never by raw UTF-16 code unit -"
// legacy-line: "  // String.prototype.slice operates on code units and can split a"
// legacy-line: "  // surrogate pair (e.g. an emoji) in half, producing a broken/lone"
// legacy-line: "  // surrogate in the rendered bubble. Array.from iterates by code point."
// legacy-line: "  const codePoints = Array.from(collapsedWhitespace);"
// legacy-line: "  if (codePoints.length <= MAX_SAFE_TASK_TITLE_LENGTH) return collapsedWhitespace;"
// legacy-line: ""
// legacy-line: "  const truncated = codePoints.slice(0, MAX_SAFE_TASK_TITLE_LENGTH).join('').trimEnd();"
// legacy-line: "  return `${truncated}...`;"
// legacy-line: "}"
// legacy-line: ""
