// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "import { isDialogueIneligible } from './sessionDedupe';"
// legacy-line: "import type { DialogueCandidate } from './types';"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Dialogue-layer-only pool scan (see usePersonalizedPetDialogue.ts): given a"
// legacy-line: " * family's ORDERED candidate pool (business ordering already applied by the"
// legacy-line: " * provider — see e.g. expiredInventoryProvider.ts), returns the first"
// legacy-line: " * candidate that is not session-seen or explicitly dismissed for `userId`,"
// legacy-line: " * or `null` if every candidate in the pool is currently ineligible."
// legacy-line: " *"
// legacy-line: " * Deliberately lives here, not in any providers/*.ts file: providers must"
// legacy-line: " * stay pure/deterministic/storage-independent (see the provider files'"
// legacy-line: " * `candidates` field docs), so all sessionStorage/localStorage-aware"
// legacy-line: " * suppression is confined to this one small helper plus sessionDedupe.ts."
// legacy-line: " *"
// legacy-line: " * No cascading/queueing: this only ever answers \"what is the correct"
// legacy-line: " * candidate for THIS evaluation\", not \"show the next one immediately after"
// legacy-line: " * this one closes\" — usePersonalizedPetDialogue.ts calls it once per family"
// legacy-line: " * per activation cycle, same as the single-candidate check it replaces."
// legacy-line: " */"
// legacy-line: "export function selectFirstEligibleDialogueCandidate("
// legacy-line: "  userId: string,"
// legacy-line: "  orderedCandidates: DialogueCandidate[]"
// legacy-line: "): DialogueCandidate | null {"
// legacy-line: "  for (const candidate of orderedCandidates) {"
// legacy-line: "    if (!isDialogueIneligible(userId, candidate.dedupeKey)) return candidate;"
// legacy-line: "  }"
// legacy-line: "  return null;"
// legacy-line: "}"
// legacy-line: ""
