// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "import { useCallback, useEffect, useRef, useState } from 'react';"
// legacy-line: "import { supabase } from '@/services/supabaseClient';"
// legacy-line: "import { useCreateAppLink } from '@/mutation/useCreateAppLink';"
// legacy-line: "import { getAuthUser } from '@/utils/authStorage';"
// legacy-line: "import { resolvePersonalizedDialogue } from './resolveDialogue';"
// legacy-line: "import { fetchInventoryDialogueEvaluation } from './providers/inventorySnapshotProvider';"
// legacy-line: "import { fetchTodoDialogueEvaluation } from './providers/todoSnapshotProvider';"
// legacy-line: "import { fetchAppointmentDialogueEvaluation } from './providers/appointmentSnapshotProvider';"
// legacy-line: "import { buildProfileCandidate } from './providers/profileProvider';"
// legacy-line: "import { fetchLegacyIntroCandidate } from './providers/legacyIntroProvider';"
// legacy-line: "import { resolveSafeFirstName } from './nameResolution';"
// legacy-line: "import { isDialogueIneligible, markDialogueDismissed, markDialogueSeenThisSession } from './sessionDedupe';"
// legacy-line: "import { selectFirstEligibleDialogueCandidate } from './selectDialogueCandidate';"
// legacy-line: "import { getInventoryAppRoute, getTodoAppRoute, getAppointmentAppRoute, getProfileSettingsRoute } from './knownRoutes';"
// legacy-line: "import { toCalendarDateKey } from './dateUtils';"
// legacy-line: "import {"
// legacy-line: "  DIALOGUE_ID,"
// legacy-line: "  PET_DIALOGUE_RULE_VERSION,"
// legacy-line: "  type DialogueCandidate,"
// legacy-line: "  type InsightCandidate,"
// legacy-line: "  type PersonalizedDialogueLifecycle,"
// legacy-line: "  type ProfileCompletionStatus,"
// legacy-line: "} from './types';"
// legacy-line: ""
// legacy-line: "const DEFAULT_FALLBACK_AUTO_CLOSE_MS = 6000;"
// legacy-line: ""
// legacy-line: "/** See providers/expiredInventoryProvider.ts's ExpiredInventoryFacts for the"
// legacy-line: " *  same design intent. `messageSource` is included because it has a real"
// legacy-line: " *  architectural purpose: distinguishing an admin-configured AIBoard message"
// legacy-line: " *  from the emergency hardcoded one is exactly the kind of provenance a"
// legacy-line: " *  future Landing Insight/Data-Driven Chat consumer would need to decide"
// legacy-line: " *  whether the wording is safe to reuse/rephrase elsewhere. */"
// legacy-line: "export interface WelcomeFallbackFacts {"
// legacy-line: "  userId: string;"
// legacy-line: "  firstName: string | null;"
// legacy-line: "  messageSource: 'aiboard' | 'hardcoded_fallback';"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "// Existing, source-proven placeholder convention for `welcome_back_text` —"
// legacy-line: "// reused verbatim from CatMascot.tsx's legacy (flag-disabled) `initDialog()`"
// legacy-line: "// welcomeBack path, which already implements this exact `[name]` substitution"
// legacy-line: "// against this exact column. Not a new placeholder syntax: this mirrors that"
// legacy-line: "// code's regex and graceful-strip-when-no-name behavior so an admin-authored"
// legacy-line: "// `[name]` works identically regardless of which code path is active."
// legacy-line: "function applyNamePlaceholder(text: string, firstName: string | null): string {"
// legacy-line: "  if (!/\\[name\\]/i.test(text)) return text;"
// legacy-line: "  return firstName"
// legacy-line: "    ? text.replace(/\\[name\\]/gi, firstName)"
// legacy-line: "    : text"
// legacy-line: "        .replace(/,\\s*\\[name\\]/gi, '')"
// legacy-line: "        .replace(/\\[name\\],\\s*/gi, '')"
// legacy-line: "        .replace(/\\[name\\]/gi, '')"
// legacy-line: "        .replace(/\\s{2,}/g, ' ')"
// legacy-line: "        .trim();"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "interface UsePersonalizedPetDialogueOptions {"
// legacy-line: "  /** Feature flag enabled AND the user is logged in (mirrors CatMascot's `!disabled`). */"
// legacy-line: "  active: boolean;"
// legacy-line: "  /**"
// legacy-line: "   * The Supabase Auth user id that App.tsx's reconcileSupabaseIdentity has"
// legacy-line: "   * confirmed belongs to the same account as the currently Odoo-verified"
// legacy-line: "   * user. Three states: `undefined` = reconciliation still in progress /"
// legacy-line: "   * not yet attempted (stay neutral — never guess); `null` = confirmed"
// legacy-line: "   * guest, or a failed/mismatched reconciliation (safe to show the neutral"
// legacy-line: "   * fallback); a string = the confirmed-matched Supabase user id. This"
// legacy-line: "   * hook never independently reads `supabase.auth.getSession()` to decide"
// legacy-line: "   * *whose* evaluation to run — App.tsx is the single owner of Odoo/"
// legacy-line: "   * Supabase identity reconciliation; this is the one canonical signal"
// legacy-line: "   * consumed here."
// legacy-line: "   */"
// legacy-line: "  matchedUserId: string | null | undefined;"
// legacy-line: "  profileStatus: ProfileCompletionStatus;"
// legacy-line: "  /** Reads the existing `intro_shown_{userId}` localStorage flag — owned by CatMascot, not duplicated here. */"
// legacy-line: "  introAlreadyCompleted: (userId: string) => boolean;"
// legacy-line: "  onNavigateInternal?: (path: string) => void;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export interface PersonalizedDialogueSelection {"
// legacy-line: "  candidate: DialogueCandidate;"
// legacy-line: "  /** Populated only when the resolved candidate is the legacy post-login intro. */"
// legacy-line: "  introSteps: string[];"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function buildFallbackCandidate(params: {"
// legacy-line: "  userId: string;"
// legacy-line: "  profileName?: string | null;"
// legacy-line: "  profileFullName?: string | null;"
// legacy-line: "  metaName?: string | null;"
// legacy-line: "  email?: string | null;"
// legacy-line: "  autoCloseMs: number;"
// legacy-line: "  /**"
// legacy-line: "   * Raw `aiboard_simulator_configs.welcome_back_text` for this evaluation,"
// legacy-line: "   * as resolved by fetchLegacyIntroCandidate — `undefined` when that fetch"
// legacy-line: "   * failed/found no config row, `null` when the row exists but the column"
// legacy-line: "   * is null, a string for any stored value (including empty/whitespace)."
// legacy-line: "   * This is the ONLY thing that decides whether AIBoard or the hardcoded"
// legacy-line: "   * text is authoritative for this candidate — see the eligibility check"
// legacy-line: "   * below (non-empty after trim)."
// legacy-line: "   */"
// legacy-line: "  configuredWelcomeBackText?: string | null;"
// legacy-line: "}): InsightCandidate<WelcomeFallbackFacts> {"
// legacy-line: "  const firstName = resolveSafeFirstName(params);"
// legacy-line: ""
// legacy-line: "  const trimmedConfigured = params.configuredWelcomeBackText?.trim() ?? '';"
// legacy-line: "  const useAiboardText = trimmedConfigured.length > 0;"
// legacy-line: ""
// legacy-line: "  // Emergency hardcoded path — byte-for-byte identical to before this"
// legacy-line: "  // change whenever AIBoard's config is missing/null/blank/whitespace-only"
// legacy-line: "  // or the config fetch itself failed. Never reached when useAiboardText."
// legacy-line: "  const hardcodedMessage = firstName ? `Welcome back, ${firstName}!` : 'Welcome back!';"
// legacy-line: "  const hardcodedMessageTemplate = 'Welcome back, {firstName}!';"
// legacy-line: ""
// legacy-line: "  // AIBoard path — the raw, untrimmed, un-rewritten admin text is the"
// legacy-line: "  // canonical template; `message` is that same text with the existing"
// legacy-line: "  // `[name]` placeholder (if present) resolved, and nothing else changed —"
// legacy-line: "  // no prepended/appended sentence, no punctuation/wording changes."
// legacy-line: "  const configuredRaw = params.configuredWelcomeBackText as string; // only read when useAiboardText"
// legacy-line: "  const message = useAiboardText ? applyNamePlaceholder(configuredRaw, firstName) : hardcodedMessage;"
// legacy-line: "  const messageTemplate = useAiboardText ? configuredRaw : hardcodedMessageTemplate;"
// legacy-line: ""
// legacy-line: "  const evaluatedAt = new Date().toISOString();"
// legacy-line: "  const facts: WelcomeFallbackFacts = {"
// legacy-line: "    userId: params.userId,"
// legacy-line: "    firstName,"
// legacy-line: "    messageSource: useAiboardText ? 'aiboard' : 'hardcoded_fallback',"
// legacy-line: "  };"
// legacy-line: ""
// legacy-line: "  return {"
// legacy-line: "    // Neutral, no-urgent-condition fallback — not tied to any one mini-app"
// legacy-line: "    // (see legacyIntroProvider.ts's identical reasoning for 'legacy')."
// legacy-line: "    app: 'system',"
// legacy-line: "    triggerId: DIALOGUE_ID.WELCOME_FALLBACK,"
// legacy-line: "    facts,"
// legacy-line: "    messageTemplate,"
// legacy-line: "    sourceRecordId: params.userId,"
// legacy-line: "    evaluatedAt,"
// legacy-line: "    userState: 'GENERAL_USER_NO_URGENT',"
// legacy-line: "    dialogueId: DIALOGUE_ID.WELCOME_FALLBACK,"
// legacy-line: "    priority: 'FALLBACK',"
// legacy-line: "    message,"
// legacy-line: "    source: { app: 'gallery', evaluatedAt },"
// legacy-line: "    dedupeKey: `welcome_fallback:${params.userId}`,"
// legacy-line: "    ruleVersion: PET_DIALOGUE_RULE_VERSION,"
// legacy-line: "    autoCloseMs: params.autoCloseMs,"
// legacy-line: "    recordId: params.userId,"
// legacy-line: "  };"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Orchestrates Phase 1A candidate evaluation and deterministic selection."
// legacy-line: " * Pure resolution logic lives in resolveDialogue.ts; this hook is only"
// legacy-line: " * responsible for fetching candidates, guarding against stale/late"
// legacy-line: " * responses, and locking the final selection for the current mount."
// legacy-line: " *"
// legacy-line: " * Identity lifecycle: every evaluation is owned by exactly one resolved,"
// legacy-line: " * reconciled user id (`matchedUserId`, supplied by App.tsx — see"
// legacy-line: " * reconcileSupabaseIdentity), one generation, and one AbortController."
// legacy-line: " * `matchedUserId` is a required dependency of the evaluation effect,"
// legacy-line: " * specifically so an identity change that doesn't happen to also flip"
// legacy-line: " * `active` or `profileStatus` — e.g. a cross-tab account switch, or an Odoo"
// legacy-line: " * re-verification whose Supabase session hadn't caught up yet — still"
// legacy-line: " * restarts evaluation. This hook deliberately does not re-derive or"
// legacy-line: " * independently verify identity matching itself: App.tsx is the single"
// legacy-line: " * owner of that reconciliation (see Section 4/11 of the identity"
// legacy-line: " * reconciliation task this comment originates from) — duplicating it here"
// legacy-line: " * would be a second, potentially-divergent implementation of the same"
// legacy-line: " * check."
// legacy-line: " */"
// legacy-line: "export function usePersonalizedPetDialogue({"
// legacy-line: "  active,"
// legacy-line: "  matchedUserId,"
// legacy-line: "  profileStatus,"
// legacy-line: "  introAlreadyCompleted,"
// legacy-line: "  onNavigateInternal,"
// legacy-line: "}: UsePersonalizedPetDialogueOptions) {"
// legacy-line: "  const [lifecycle, setLifecycle] = useState<PersonalizedDialogueLifecycle>('idle');"
// legacy-line: "  const [selection, setSelection] = useState<PersonalizedDialogueSelection | null>(null);"
// legacy-line: "  const [userId, setUserId] = useState<string | null>(null);"
// legacy-line: ""
// legacy-line: "  const generationRef = useRef(0);"
// legacy-line: "  const lockedUserIdRef = useRef<string | null>(null);"
// legacy-line: "  const { mutateAsync: createAppLink } = useCreateAppLink();"
// legacy-line: ""
// legacy-line: "  // Mirrors the `matchedUserId` prop synchronously during render (not via a"
// legacy-line: "  // separate effect, which would lag a tick behind) — defense-in-depth so"
// legacy-line: "  // an in-flight evaluation's stale check can observe an identity change"
// legacy-line: "  // the instant this component re-renders with a new prop value, not only"
// legacy-line: "  // after this hook's own effect has had a chance to clean up and restart."
// legacy-line: "  const latestMatchedUserIdRef = useRef(matchedUserId);"
// legacy-line: "  latestMatchedUserIdRef.current = matchedUserId;"
// legacy-line: ""
// legacy-line: "  // Appointment eligibility changes purely as clinic-device time advances,"
// legacy-line: "  // with no data change to react to — so, unlike every other provider here,"
// legacy-line: "  // it needs an explicit \"re-evaluate now\" trigger beyond identity/profile"
// legacy-line: "  // changes. `refreshTick` is that trigger: bumped (debounced/coalesced) on"
// legacy-line: "  // window focus and document visibility, gated to only when a real"
// legacy-line: "  // identity is confirmed matched. It's just another dependency of the same"
// legacy-line: "  // evaluation effect below, so it reuses 100% of the existing generation/"
// legacy-line: "  // abort/staleness machinery — a refresh is exactly a normal re-run, not a"
// legacy-line: "  // separate code path. Per the approved Phase scope: no interval polling,"
// legacy-line: "  // no per-minute timer — a continuously focused page will not itself cross"
// legacy-line: "  // the two-hour threshold until one of these triggers (or a"
// legacy-line: "  // matchedUserId/profileStatus change) fires again."
// legacy-line: "  const [refreshTick, setRefreshTick] = useState(0);"
// legacy-line: "  const refreshDebounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);"
// legacy-line: ""
// legacy-line: "  useEffect(() => {"
// legacy-line: "    if (!active || typeof matchedUserId !== 'string') return;"
// legacy-line: ""
// legacy-line: "    const REFRESH_DEBOUNCE_MS = 1000;"
// legacy-line: "    const scheduleRefresh = () => {"
// legacy-line: "      if (refreshDebounceRef.current !== null) clearTimeout(refreshDebounceRef.current);"
// legacy-line: "      refreshDebounceRef.current = setTimeout(() => {"
// legacy-line: "        refreshDebounceRef.current = null;"
// legacy-line: "        setRefreshTick((t) => t + 1);"
// legacy-line: "      }, REFRESH_DEBOUNCE_MS);"
// legacy-line: "    };"
// legacy-line: ""
// legacy-line: "    const onFocus = () => scheduleRefresh();"
// legacy-line: "    const onVisibilityChange = () => {"
// legacy-line: "      if (document.visibilityState === 'visible') scheduleRefresh();"
// legacy-line: "    };"
// legacy-line: ""
// legacy-line: "    window.addEventListener('focus', onFocus);"
// legacy-line: "    document.addEventListener('visibilitychange', onVisibilityChange);"
// legacy-line: ""
// legacy-line: "    return () => {"
// legacy-line: "      window.removeEventListener('focus', onFocus);"
// legacy-line: "      document.removeEventListener('visibilitychange', onVisibilityChange);"
// legacy-line: "      if (refreshDebounceRef.current !== null) {"
// legacy-line: "        clearTimeout(refreshDebounceRef.current);"
// legacy-line: "        refreshDebounceRef.current = null;"
// legacy-line: "      }"
// legacy-line: "    };"
// legacy-line: "  }, [active, matchedUserId]);"
// legacy-line: ""
// legacy-line: "  useEffect(() => {"
// legacy-line: "    if (!active) {"
// legacy-line: "      setLifecycle('idle');"
// legacy-line: "      setSelection(null);"
// legacy-line: "      setUserId(null);"
// legacy-line: "      lockedUserIdRef.current = null;"
// legacy-line: "      return;"
// legacy-line: "    }"
// legacy-line: ""
// legacy-line: "    if (matchedUserId === undefined) {"
// legacy-line: "      // App.tsx is still reconciling Odoo/Supabase identity (or hasn't"
// legacy-line: "      // attempted it yet for the current Odoo session) — stay neutral"
// legacy-line: "      // rather than guessing; this effect re-runs the instant App.tsx"
// legacy-line: "      // resolves it (to a matched id, or a confirmed `null`), since"
// legacy-line: "      // `matchedUserId` is a dependency."
// legacy-line: "      setLifecycle('loading');"
// legacy-line: "      setSelection(null);"
// legacy-line: "      setUserId(null);"
// legacy-line: "      lockedUserIdRef.current = null;"
// legacy-line: "      return;"
// legacy-line: "    }"
// legacy-line: ""
// legacy-line: "    // Captured once per generation — every check below compares against"
// legacy-line: "    // this frozen value, never against the live `matchedUserId` closure"
// legacy-line: "    // variable (which belongs to whichever render scheduled this effect,"
// legacy-line: "    // not to \"right now\")."
// legacy-line: "    const capturedUserId = matchedUserId;"
// legacy-line: "    const generation = ++generationRef.current;"
// legacy-line: "    const controller = new AbortController();"
// legacy-line: "    let cancelled = false;"
// legacy-line: ""
// legacy-line: "    setLifecycle('loading');"
// legacy-line: "    setSelection(null);"
// legacy-line: "    // Set synchronously (not lazily inside the async run() below) so"
// legacy-line: "    // `userId` — exposed to CatMascot as `personalizedUserId` — reflects"
// legacy-line: "    // the identity change in the same commit the evaluation restarts, not"
// legacy-line: "    // only once a new async evaluation eventually resolves. This is what"
// legacy-line: "    // lets CatMascot detect \"the user changed\" promptly enough to tear"
// legacy-line: "    // down an already-adopted previous-user dialogue."
// legacy-line: "    setUserId(capturedUserId);"
// legacy-line: "    lockedUserIdRef.current = capturedUserId;"
// legacy-line: ""
// legacy-line: "    // Generation match is the primary guard (bumped on every effect"
// legacy-line: "    // restart, including every matchedUserId change). The identity-ref"
// legacy-line: "    // comparison is deliberate defense-in-depth per the required lifecycle"
// legacy-line: "    // guarantee — never rely on generation matching alone to prove the"
// legacy-line: "    // captured user is still current."
// legacy-line: "    const isStale = () => cancelled || generation !== generationRef.current || latestMatchedUserIdRef.current !== capturedUserId;"
// legacy-line: ""
// legacy-line: "    if (!capturedUserId) {"
// legacy-line: "      // No confirmed-matched identity — either a guest, or Odoo/Supabase"
// legacy-line: "      // identity reconciliation hasn't completed (or failed/mismatched)."
// legacy-line: "      // Not enough *trustworthy* identity to safely scope any query, so go"
// legacy-line: "      // straight to the hardcoded fallback rather than guessing at another"
// legacy-line: "      // account's data or querying with a not-yet-confirmed session."
// legacy-line: "      setLifecycle('failed');"
// legacy-line: "      setSelection({"
// legacy-line: "        candidate: buildFallbackCandidate({ userId: 'anonymous', autoCloseMs: DEFAULT_FALLBACK_AUTO_CLOSE_MS }),"
// legacy-line: "        introSteps: [],"
// legacy-line: "      });"
// legacy-line: "      return () => {"
// legacy-line: "        cancelled = true;"
// legacy-line: "        controller.abort();"
// legacy-line: "      };"
// legacy-line: "    }"
// legacy-line: ""
// legacy-line: "    const run = async () => {"
// legacy-line: "      try {"
// legacy-line: "        // Cosmetic display-name inputs only (never the identity/security"
// legacy-line: "        // boundary — that's `capturedUserId`, already confirmed matched by"
// legacy-line: "        // App.tsx). Reading the session fresh here is safe: by definition"
// legacy-line: "        // `capturedUserId` is non-null only once App.tsx has confirmed the"
// legacy-line: "        // current Supabase session belongs to this exact account."
// legacy-line: "        const {"
// legacy-line: "          data: { session },"
// legacy-line: "        } = await supabase.auth.getSession();"
// legacy-line: "        if (isStale()) return;"
// legacy-line: "        const metaName = (session?.user?.user_metadata as { name?: string } | undefined)?.name ?? null;"
// legacy-line: "        const email = session?.user?.email ?? null;"
// legacy-line: ""
// legacy-line: "        const fetchDisplayNameProfile = async (): Promise<{ name?: string | null; full_name?: string | null } | null> => {"
// legacy-line: "          try {"
// legacy-line: "            const { data } = await supabase"
// legacy-line: "              .from('profiles')"
// legacy-line: "              .select('name, full_name')"
// legacy-line: "              .eq('user_id', capturedUserId)"
// legacy-line: "              .maybeSingle();"
// legacy-line: "            return data;"
// legacy-line: "          } catch {"
// legacy-line: "            return null;"
// legacy-line: "          }"
// legacy-line: "        };"
// legacy-line: ""
// legacy-line: "        // One local clock snapshot for the whole evaluation — Todo's"
// legacy-line: "        // localToday and the Appointment provider's query window/2-hour"
// legacy-line: "        // check all derive from this same instant, so a single evaluation"
// legacy-line: "        // is always internally consistent even if it happens to straddle"
// legacy-line: "        // local midnight while in flight (a later refresh — see"
// legacy-line: "        // refreshTick above — captures a fresh instant for its own run)."
// legacy-line: "        const evaluationNow = new Date();"
// legacy-line: "        const localToday = toCalendarDateKey(evaluationNow);"
// legacy-line: ""
// legacy-line: "        const [inventoryResult, todoResult, appointmentResult, introResult, profileRow] = await Promise.all(["
// legacy-line: "          fetchInventoryDialogueEvaluation(capturedUserId, controller.signal),"
// legacy-line: "          fetchTodoDialogueEvaluation(capturedUserId, localToday, controller.signal),"
// legacy-line: "          fetchAppointmentDialogueEvaluation(capturedUserId, evaluationNow, controller.signal),"
// legacy-line: "          fetchLegacyIntroCandidate(capturedUserId, introAlreadyCompleted(capturedUserId), controller.signal),"
// legacy-line: "          fetchDisplayNameProfile(),"
// legacy-line: "        ]);"
// legacy-line: ""
// legacy-line: "        if (isStale()) return;"
// legacy-line: ""
// legacy-line: "        if (inventoryResult.status === 'aborted' || todoResult.status === 'aborted' || appointmentResult.status === 'aborted') {"
// legacy-line: "          // The shared per-evaluation controller was aborted (unmount, user"
// legacy-line: "          // change, or a newer generation) — isStale() above should already"
// legacy-line: "          // have caught this, but bail out explicitly rather than act on a"
// legacy-line: "          // cancelled evaluation's result under any circumstance."
// legacy-line: "          return;"
// legacy-line: "        }"
// legacy-line: ""
// legacy-line: "        const fallback = buildFallbackCandidate({"
// legacy-line: "          userId: capturedUserId,"
// legacy-line: "          profileName: profileRow?.name,"
// legacy-line: "          profileFullName: profileRow?.full_name,"
// legacy-line: "          metaName,"
// legacy-line: "          email,"
// legacy-line: "          autoCloseMs: DEFAULT_FALLBACK_AUTO_CLOSE_MS,"
// legacy-line: "          // Reuses the same aiboard_simulator_configs row fetchLegacyIntroCandidate"
// legacy-line: "          // already resolved above (Promise.all) — no second config query."
// legacy-line: "          // Independent of inventory/todo/appointment's own success/failure"
// legacy-line: "          // below: this fallback should still use the configured AIBoard"
// legacy-line: "          // wording even when one of those three providers failed."
// legacy-line: "          configuredWelcomeBackText: introResult.welcomeBackText,"
// legacy-line: "        });"
// legacy-line: ""
// legacy-line: "        if (inventoryResult.status === 'failed' || todoResult.status === 'failed' || appointmentResult.status === 'failed') {"
// legacy-line: "          // A provider failure is never \"no urgent inventory/tasks/"
// legacy-line: "          // appointments exist\" — it's unknown. With three independent"
// legacy-line: "          // urgent-data providers now in play, any one failing must fail"
// legacy-line: "          // the whole evaluation closed: never show Profile/P1/P2/Intro"
// legacy-line: "          // while a real P0/P1 could be hidden behind another provider's"
// legacy-line: "          // failure. Go straight to the neutral fallback (no timeout/error"
// legacy-line: "          // wording — buildFallbackCandidate's message is identical"
// legacy-line: "          // regardless of why the evaluation couldn't be trusted)."
// legacy-line: "          if (inventoryResult.status === 'failed') {"
// legacy-line: "            console.warn('[petDialogue] inventory evaluation failed, reason:', inventoryResult.reason);"
// legacy-line: "          }"
// legacy-line: "          if (todoResult.status === 'failed') {"
// legacy-line: "            console.warn('[petDialogue] todo evaluation failed, reason:', todoResult.reason);"
// legacy-line: "          }"
// legacy-line: "          if (appointmentResult.status === 'failed') {"
// legacy-line: "            console.warn('[petDialogue] appointment evaluation failed, reason:', appointmentResult.reason);"
// legacy-line: "          }"
// legacy-line: "          if (isStale()) return;"
// legacy-line: "          setLifecycle('failed');"
// legacy-line: "          setSelection({ candidate: fallback, introSteps: [] });"
// legacy-line: "          return;"
// legacy-line: "        }"
// legacy-line: ""
// legacy-line: "        const { expiredCandidates, expiringSoonCandidates, lowStockCandidates } = inventoryResult.candidate;"
// legacy-line: "        const { overdueCandidates, taskTodayCandidates } = todoResult.candidate;"
// legacy-line: "        const { appointmentSoonCandidates } = appointmentResult.candidate;"
// legacy-line: ""
// legacy-line: "        // Explicit P0 subtype rank: expired inventory always outranks an"
// legacy-line: "        // overdue High task. Resolved here, before either reaches the"
// legacy-line: "        // shared resolver, so resolveDialogue.ts never has to compare an"
// legacy-line: "        // inventory expiry date against a Todo task date — at most one P0"
// legacy-line: "        // candidate is ever passed into it."
// legacy-line: "        //"
// legacy-line: "        // Dismissal-aware pool scan (starvation fix): each family may have"
// legacy-line: "        // several simultaneously business-eligible records (e.g. two"
// legacy-line: "        // independently expired items). The provider already returns them"
// legacy-line: "        // in business order (see expiredInventoryProvider.ts /"
// legacy-line: "        // overdueTaskProvider.ts); selectFirstEligibleDialogueCandidate just"
// legacy-line: "        // skips session-seen/dismissed entries and returns the first"
// legacy-line: "        // remaining one, so dismissing the winner reveals the next"
// legacy-line: "        // same-family candidate instead of incorrectly falling through to a"
// legacy-line: "        // lower-priority family. No queueing: this is re-evaluated once per"
// legacy-line: "        // activation cycle, same as the single-candidate check it replaces."
// legacy-line: "        const unhandledExpired = selectFirstEligibleDialogueCandidate(capturedUserId, expiredCandidates);"
// legacy-line: "        const unhandledOverdueTask = selectFirstEligibleDialogueCandidate(capturedUserId, overdueCandidates);"
// legacy-line: "        const p0 = unhandledExpired ?? unhandledOverdueTask;"
// legacy-line: ""
// legacy-line: "        if (p0) {"
// legacy-line: "          // A real P0 candidate always wins immediately — never wait on"
// legacy-line: "          // profile status."
// legacy-line: "          if (isStale()) return;"
// legacy-line: "          setLifecycle('ready');"
// legacy-line: "          setSelection({ candidate: p0, introSteps: [] });"
// legacy-line: "          return;"
// legacy-line: "        }"
// legacy-line: ""
// legacy-line: "        // Explicit P1 subtype rank: Appointment Within 2 Hours always"
// legacy-line: "        // outranks High Task Today. Resolved here, before either ever"
// legacy-line: "        // reaches the shared resolver, exactly like the P0 subtypes above —"
// legacy-line: "        // an appointment start instant is never compared against a Todo"
// legacy-line: "        // due-date to decide this."
// legacy-line: "        const unhandledAppointmentSoon = selectFirstEligibleDialogueCandidate(capturedUserId, appointmentSoonCandidates);"
// legacy-line: "        const unhandledHighTaskToday = selectFirstEligibleDialogueCandidate(capturedUserId, taskTodayCandidates);"
// legacy-line: "        const p1 = unhandledAppointmentSoon ?? unhandledHighTaskToday;"
// legacy-line: ""
// legacy-line: "        if (p1) {"
// legacy-line: "          // Per the approved priority order, P1 (Appointment Soon / High"
// legacy-line: "          // Task Today) also always wins immediately — it outranks Profile,"
// legacy-line: "          // so it must never wait on profile status either."
// legacy-line: "          if (isStale()) return;"
// legacy-line: "          setLifecycle('ready');"
// legacy-line: "          setSelection({ candidate: p1, introSteps: [] });"
// legacy-line: "          return;"
// legacy-line: "        }"
// legacy-line: ""
// legacy-line: "        // No selectable P0 or P1. Wait for profile completeness before"
// legacy-line: "        // deciding among Profile / P2 / Intro / Fallback — an \"incomplete\""
// legacy-line: "        // result must still outrank P2 and the legacy intro. The effect"
// legacy-line: "        // re-runs when profileStatus changes."
// legacy-line: "        if (profileStatus === 'loading') {"
// legacy-line: "          return;"
// legacy-line: "        }"
// legacy-line: ""
// legacy-line: "        const profileCandidateRaw = buildProfileCandidate(profileStatus, capturedUserId);"
// legacy-line: "        const profileCandidate = isDialogueIneligible(capturedUserId, profileCandidateRaw?.dedupeKey ?? '')"
// legacy-line: "          ? null"
// legacy-line: "          : profileCandidateRaw;"
// legacy-line: ""
// legacy-line: "        // Dismissal dedupe is applied independently to each P2 subtype before"
// legacy-line: "        // choosing between them — a handled Low Stock must not block an"
// legacy-line: "        // otherwise-eligible Expiring Soon candidate on a different item,"
// legacy-line: "        // and vice versa."
// legacy-line: "        const unhandledLowStock = selectFirstEligibleDialogueCandidate(capturedUserId, lowStockCandidates);"
// legacy-line: "        const unhandledExpiringSoon = selectFirstEligibleDialogueCandidate(capturedUserId, expiringSoonCandidates);"
// legacy-line: ""
// legacy-line: "        // Explicit P2 subtype rank (approved reversal): Low Stock now"
// legacy-line: "        // outranks Expiring Soon. Resolved here, before either ever reaches"
// legacy-line: "        // the shared resolver, so resolveDialogue.ts never has to compare a"
// legacy-line: "        // quantity-based candidate (no eventTime) against an expiry date."
// legacy-line: "        const p2 = unhandledLowStock ?? unhandledExpiringSoon;"
// legacy-line: ""
// legacy-line: "        // Priority ordering (PROFILE > P2 > LEGACY_INTRO > FALLBACK) lives"
// legacy-line: "        // entirely in resolveDialogue.ts's PRIORITY_RANK — passing all"
// legacy-line: "        // remaining candidates here rather than branching on profileStatus"
// legacy-line: "        // ourselves keeps that ranking the single source of truth."
// legacy-line: "        const resolved = resolvePersonalizedDialogue([profileCandidate, p2, introResult.candidate], fallback);"
// legacy-line: ""
// legacy-line: "        if (isStale()) return;"
// legacy-line: "        setLifecycle('ready');"
// legacy-line: "        setSelection({"
// legacy-line: "          candidate: resolved,"
// legacy-line: "          introSteps: resolved.dialogueId === DIALOGUE_ID.LEGACY_POST_LOGIN_INTRO ? introResult.steps : [],"
// legacy-line: "        });"
// legacy-line: "      } catch (err) {"
// legacy-line: "        if (isStale()) return;"
// legacy-line: "        console.warn('[petDialogue] evaluation failed, using fallback:', err);"
// legacy-line: "        setLifecycle('failed');"
// legacy-line: "        setSelection({"
// legacy-line: "          candidate: buildFallbackCandidate({"
// legacy-line: "            userId: capturedUserId,"
// legacy-line: "            autoCloseMs: DEFAULT_FALLBACK_AUTO_CLOSE_MS,"
// legacy-line: "          }),"
// legacy-line: "          introSteps: [],"
// legacy-line: "        });"
// legacy-line: "      }"
// legacy-line: "    };"
// legacy-line: ""
// legacy-line: "    run();"
// legacy-line: ""
// legacy-line: "    return () => {"
// legacy-line: "      cancelled = true;"
// legacy-line: "      controller.abort();"
// legacy-line: "    };"
// legacy-line: "    // profileStatus is intentionally a dependency: while it's 'loading' the"
// legacy-line: "    // run above returns early without resolving, and must re-run once a real"
// legacy-line: "    // status arrives so PROFILE can still outrank LEGACY_INTRO/FALLBACK."
// legacy-line: "    // matchedUserId is intentionally a dependency: it's the sole identity"
// legacy-line: "    // signal this effect restarts on — see the hook-level comment above for"
// legacy-line: "    // why active/profileStatus alone are not sufficient, and why this hook"
// legacy-line: "    // consumes App.tsx's reconciled identity rather than tracking its own."
// legacy-line: "    // refreshTick is intentionally a dependency: it's the sole trigger for"
// legacy-line: "    // re-evaluating Appointment eligibility as clinic-device time advances"
// legacy-line: "    // (see the focus/visibility effect above) — a refresh is just another"
// legacy-line: "    // ordinary re-run of this same effect, gaining the exact same"
// legacy-line: "    // generation/abort/staleness guarantees as every other restart."
// legacy-line: "    // eslint-disable-next-line react-hooks/exhaustive-deps"
// legacy-line: "  }, [active, matchedUserId, profileStatus, refreshTick]);"
// legacy-line: ""
// legacy-line: "  // Show-time mark: same-tab/session ONLY (sessionStorage). Merely"
// legacy-line: "  // displaying a candidate must never suppress it in another tab — only an"
// legacy-line: "  // explicit Close or CTA does that (see runAction below, and"
// legacy-line: "  // CatMascot.tsx's closeDialog)."
// legacy-line: "  const markShown = useCallback((candidate: DialogueCandidate) => {"
// legacy-line: "    const uid = lockedUserIdRef.current;"
// legacy-line: "    if (!uid) return;"
// legacy-line: "    if ("
// legacy-line: "      candidate.priority === 'P0' ||"
// legacy-line: "      candidate.priority === 'PROFILE' ||"
// legacy-line: "      candidate.priority === 'P1' ||"
// legacy-line: "      candidate.priority === 'P2'"
// legacy-line: "    ) {"
// legacy-line: "      markDialogueSeenThisSession(uid, candidate.dedupeKey);"
// legacy-line: "    }"
// legacy-line: "  }, []);"
// legacy-line: ""
// legacy-line: "  const runAction = useCallback("
// legacy-line: "    async (candidate: DialogueCandidate) => {"
// legacy-line: "      // CTA = explicit user action: write the cross-tab dismissal FIRST,"
// legacy-line: "      // synchronously, before any navigation below."
// legacy-line: "      const uid = lockedUserIdRef.current;"
// legacy-line: "      if (uid) markDialogueDismissed(uid, candidate.dedupeKey);"
// legacy-line: ""
// legacy-line: "      if (candidate.dialogueId === DIALOGUE_ID.PROFILE_INCOMPLETE) {"
// legacy-line: "        onNavigateInternal?.(getProfileSettingsRoute());"
// legacy-line: "        return;"
// legacy-line: "      }"
// legacy-line: ""
// legacy-line: "      if ("
// legacy-line: "        candidate.dialogueId === DIALOGUE_ID.EXPIRED_INVENTORY ||"
// legacy-line: "        candidate.dialogueId === DIALOGUE_ID.INVENTORY_EXPIRING_SOON ||"
// legacy-line: "        candidate.dialogueId === DIALOGUE_ID.INVENTORY_LOW_STOCK"
// legacy-line: "      ) {"
// legacy-line: "        const authUser = getAuthUser();"
// legacy-line: "        // Open the tab synchronously (before any await) so popup blockers"
// legacy-line: "        // treat it as part of the click gesture — same pattern as AppCard."
// legacy-line: "        const w = window.open('', '_blank');"
// legacy-line: "        if (!authUser?.username) {"
// legacy-line: "          if (w) w.location.href = getInventoryAppRoute();"
// legacy-line: "          return;"
// legacy-line: "        }"
// legacy-line: "        try {"
// legacy-line: "          const res = (await createAppLink({ app: 'inventory', email: authUser.username, name: authUser.name })) as {"
// legacy-line: "            result?: { url?: string };"
// legacy-line: "          };"
// legacy-line: "          const url = res?.result?.url;"
// legacy-line: "          if (w) w.location.href = url || getInventoryAppRoute();"
// legacy-line: "        } catch {"
// legacy-line: "          if (w) w.location.href = getInventoryAppRoute();"
// legacy-line: "        }"
// legacy-line: "        return;"
// legacy-line: "      }"
// legacy-line: ""
// legacy-line: "      if (candidate.dialogueId === DIALOGUE_ID.OVERDUE_HIGH_TASK || candidate.dialogueId === DIALOGUE_ID.HIGH_TASK_TODAY) {"
// legacy-line: "        const authUser = getAuthUser();"
// legacy-line: "        // Same pattern as the Inventory branch above — always the Todo"
// legacy-line: "        // landing page, never a task-detail path (no such controlled route"
// legacy-line: "        // exists)."
// legacy-line: "        const w = window.open('', '_blank');"
// legacy-line: "        if (!authUser?.username) {"
// legacy-line: "          if (w) w.location.href = getTodoAppRoute();"
// legacy-line: "          return;"
// legacy-line: "        }"
// legacy-line: "        try {"
// legacy-line: "          const res = (await createAppLink({ app: 'todo', email: authUser.username, name: authUser.name })) as {"
// legacy-line: "            result?: { url?: string };"
// legacy-line: "          };"
// legacy-line: "          const url = res?.result?.url;"
// legacy-line: "          if (w) w.location.href = url || getTodoAppRoute();"
// legacy-line: "        } catch {"
// legacy-line: "          if (w) w.location.href = getTodoAppRoute();"
// legacy-line: "        }"
// legacy-line: "        return;"
// legacy-line: "      }"
// legacy-line: ""
// legacy-line: "      if (candidate.dialogueId === DIALOGUE_ID.APPOINTMENT_SOON) {"
// legacy-line: "        const authUser = getAuthUser();"
// legacy-line: "        // Same pattern as the Inventory/Todo branches above — always the"
// legacy-line: "        // Appointment landing page, never a record-specific route (no such"
// legacy-line: "        // controlled destination exists)."
// legacy-line: "        const w = window.open('', '_blank');"
// legacy-line: "        if (!authUser?.username) {"
// legacy-line: "          if (w) w.location.href = getAppointmentAppRoute();"
// legacy-line: "          return;"
// legacy-line: "        }"
// legacy-line: "        try {"
// legacy-line: "          const res = (await createAppLink({ app: 'appointment', email: authUser.username, name: authUser.name })) as {"
// legacy-line: "            result?: { url?: string };"
// legacy-line: "          };"
// legacy-line: "          const url = res?.result?.url;"
// legacy-line: "          if (w) w.location.href = url || getAppointmentAppRoute();"
// legacy-line: "        } catch {"
// legacy-line: "          if (w) w.location.href = getAppointmentAppRoute();"
// legacy-line: "        }"
// legacy-line: "        return;"
// legacy-line: "      }"
// legacy-line: ""
// legacy-line: "      // Unknown dialogueId — should never happen for a resolver-produced"
// legacy-line: "      // candidate. Deliberately do nothing rather than trusting an"
// legacy-line: "      // unvalidated route string."
// legacy-line: "    },"
// legacy-line: "    [onNavigateInternal, createAppLink]"
// legacy-line: "  );"
// legacy-line: ""
// legacy-line: "  return { lifecycle, selection, userId, markShown, runAction };"
// legacy-line: "}"
// legacy-line: ""
