// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "import { buildClinicDeviceLocalAppointmentStart, toCanonicalLocalStartTime } from '../appointmentTimeUtils';"
// legacy-line: "import { getAppointmentAppRoute } from '../knownRoutes';"
// legacy-line: "import { DIALOGUE_ID, PET_DIALOGUE_RULE_VERSION } from '../types';"
// legacy-line: "import type { DialogueCandidate, InsightCandidate } from '../types';"
// legacy-line: "import type { AppointmentSnapshot, AppointmentSnapshotRow } from './appointmentSnapshotProvider';"
// legacy-line: ""
// legacy-line: "/** See expiredInventoryProvider.ts's ExpiredInventoryFacts for the same"
// legacy-line: " *  design intent. Deliberately contains no patient name/phone/email/DOB/"
// legacy-line: " *  medical/notes fields — appointmentSnapshotProvider.ts's Supabase select"
// legacy-line: " *  never fetches them, and this refactor does not broaden that select. */"
// legacy-line: "export interface AppointmentSoonFacts {"
// legacy-line: "  appointmentId: string;"
// legacy-line: "  /** Clinic-device-local ISO instant — identical to `eventTime` below. */"
// legacy-line: "  startAt: string;"
// legacy-line: "  /** Normalized (trimmed, lowercased) status — the exact value eligibility"
// legacy-line: "   *  was actually decided on, see isEligibleStatus below. */"
// legacy-line: "  status: string;"
// legacy-line: "  minutesUntilStart: number;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Pure P1 (appointment within 2 hours) evaluation over the"
// legacy-line: " * AppointmentSnapshot — no Supabase access here. Clinic-device-local only:"
// legacy-line: " * both `date`/`start_time` and `evaluationNow` are plain local `Date`"
// legacy-line: " * values, never converted through UTC."
// legacy-line: " */"
// legacy-line: ""
// legacy-line: "export const APPOINTMENT_SOON_WINDOW_MS = 2 * 60 * 60 * 1000;"
// legacy-line: ""
// legacy-line: "const ELIGIBLE_STATUSES = new Set(['confirmed', 'scheduled']);"
// legacy-line: ""
// legacy-line: "interface QualifyingAppointmentSource {"
// legacy-line: "  appointmentId: string;"
// legacy-line: "  start: Date;"
// legacy-line: "  createdTime: string | null;"
// legacy-line: "  /** Normalized status this source actually qualified on — see"
// legacy-line: "   *  isEligibleStatus below. Carried through purely for facts exposure. */"
// legacy-line: "  status: string;"
// legacy-line: "  /** Already-checked (0, APPOINTMENT_SOON_WINDOW_MS] gap, in ms — carried"
// legacy-line: "   *  through so buildCandidateFromSource can expose minutesUntilStart"
// legacy-line: "   *  without needing a second `evaluationNow` reference. */"
// legacy-line: "  differenceMs: number;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function isEligibleStatus(status: string | null): boolean {"
// legacy-line: "  if (typeof status !== 'string') return false;"
// legacy-line: "  return ELIGIBLE_STATUSES.has(status.trim().toLowerCase());"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function selectQualifyingSource(row: AppointmentSnapshotRow, evaluationNow: Date): QualifyingAppointmentSource | null {"
// legacy-line: "  if (!row.id) return null;"
// legacy-line: "  if (!isEligibleStatus(row.status)) return null;"
// legacy-line: ""
// legacy-line: "  const start = buildClinicDeviceLocalAppointmentStart(row.date, row.start_time);"
// legacy-line: "  if (!start) return null;"
// legacy-line: ""
// legacy-line: "  const differenceMs = start.getTime() - evaluationNow.getTime();"
// legacy-line: "  if (differenceMs <= 0) return null; // already started or exactly now"
// legacy-line: "  if (differenceMs > APPOINTMENT_SOON_WINDOW_MS) return null;"
// legacy-line: ""
// legacy-line: "  return {"
// legacy-line: "    appointmentId: row.id,"
// legacy-line: "    start,"
// legacy-line: "    createdTime: row.created_at,"
// legacy-line: "    status: (row.status as string).trim().toLowerCase(),"
// legacy-line: "    differenceMs,"
// legacy-line: "  };"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "// Lexicographically greater than any real ISO-8601 timestamp string, used"
// legacy-line: "// as the sentinel sort key for a missing/malformed `created_at` — the same"
// legacy-line: "// approach as todoTaskFilters.ts's compareByCreatedTimeThenTaskId, so a"
// legacy-line: "// data gap never silently wins a selection tie."
// legacy-line: "const MISSING_CREATED_TIME_SORT_SENTINEL = String.fromCharCode(0xffff);"
// legacy-line: ""
// legacy-line: "function createdTimeSortKey(createdTime: string | null): string {"
// legacy-line: "  return createdTime || MISSING_CREATED_TIME_SORT_SENTINEL;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function compareSourcesForSelection(a: QualifyingAppointmentSource, b: QualifyingAppointmentSource): number {"
// legacy-line: "  // Earliest local appointment start wins first."
// legacy-line: "  const aStart = a.start.getTime();"
// legacy-line: "  const bStart = b.start.getTime();"
// legacy-line: "  if (aStart !== bStart) return aStart - bStart;"
// legacy-line: ""
// legacy-line: "  const aCreated = createdTimeSortKey(a.createdTime);"
// legacy-line: "  const bCreated = createdTimeSortKey(b.createdTime);"
// legacy-line: "  if (aCreated !== bCreated) return aCreated < bCreated ? -1 : 1;"
// legacy-line: ""
// legacy-line: "  return a.appointmentId < b.appointmentId ? -1 : a.appointmentId > b.appointmentId ? 1 : 0;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function buildCandidateFromSource(source: QualifyingAppointmentSource): InsightCandidate<AppointmentSoonFacts> {"
// legacy-line: "  let formattedTime: string;"
// legacy-line: "  try {"
// legacy-line: "    formattedTime = new Intl.DateTimeFormat(undefined, {"
// legacy-line: "      hour: 'numeric',"
// legacy-line: "      minute: '2-digit',"
// legacy-line: "    }).format(source.start);"
// legacy-line: "  } catch {"
// legacy-line: "    formattedTime = '';"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  // Only if a valid, already-qualified appointment's time unexpectedly"
// legacy-line: "  // fails to format — the qualification itself never depends on this."
// legacy-line: "  const message = formattedTime ? `You have an appointment at ${formattedTime}.` : 'You have an appointment starting soon.';"
// legacy-line: "  const messageTemplate = 'You have an appointment at {startTime}.';"
// legacy-line: ""
// legacy-line: "  const canonicalStartTime = toCanonicalLocalStartTime(source.start);"
// legacy-line: "  const dateKey = `${source.start.getFullYear()}-${String(source.start.getMonth() + 1).padStart(2, '0')}-${String("
// legacy-line: "    source.start.getDate()"
// legacy-line: "  ).padStart(2, '0')}`;"
// legacy-line: ""
// legacy-line: "  const evaluatedAt = new Date().toISOString();"
// legacy-line: "  const startAt = source.start.toISOString();"
// legacy-line: "  const facts: AppointmentSoonFacts = {"
// legacy-line: "    appointmentId: source.appointmentId,"
// legacy-line: "    startAt,"
// legacy-line: "    status: source.status,"
// legacy-line: "    minutesUntilStart: Math.round(source.differenceMs / 60_000),"
// legacy-line: "  };"
// legacy-line: ""
// legacy-line: "  return {"
// legacy-line: "    app: 'appointments',"
// legacy-line: "    triggerId: DIALOGUE_ID.APPOINTMENT_SOON,"
// legacy-line: "    facts,"
// legacy-line: "    messageTemplate,"
// legacy-line: "    sourceRecordId: source.appointmentId,"
// legacy-line: "    evaluatedAt,"
// legacy-line: "    userState: 'ACTIVE_USER_URGENT',"
// legacy-line: "    dialogueId: DIALOGUE_ID.APPOINTMENT_SOON,"
// legacy-line: "    priority: 'P1',"
// legacy-line: "    message,"
// legacy-line: "    action: { label: 'View Appointment', route: getAppointmentAppRoute() },"
// legacy-line: "    source: {"
// legacy-line: "      app: 'appointment',"
// legacy-line: "      recordId: source.appointmentId,"
// legacy-line: "      evaluatedAt,"
// legacy-line: "    },"
// legacy-line: "    dedupeKey: `appointment_soon:${source.appointmentId}:start:${dateKey}T${canonicalStartTime}`,"
// legacy-line: "    ruleVersion: PET_DIALOGUE_RULE_VERSION,"
// legacy-line: "    // Does not bypass the entry walk and does not auto-close — an ordinary"
// legacy-line: "    // P1 dialogue, waits like Todo's High Task Today."
// legacy-line: "    eventTime: startAt,"
// legacy-line: "    createdTime: source.createdTime ?? undefined,"
// legacy-line: "    recordId: source.appointmentId,"
// legacy-line: "  };"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export interface AppointmentSoonEvaluation {"
// legacy-line: "  candidate: DialogueCandidate | null;"
// legacy-line: "  /** Every independently eligible Appointment Soon candidate, in the same"
// legacy-line: "   *  business order compareSourcesForSelection already produces —"
// legacy-line: "   *  `candidates[0]` is always identical to `candidate` above. Additive"
// legacy-line: "   *  only. */"
// legacy-line: "  candidates: DialogueCandidate[];"
// legacy-line: "  qualifyingAppointmentIds: Set<string>;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export function evaluateAppointmentSoon(snapshot: AppointmentSnapshot, evaluationNow: Date): AppointmentSoonEvaluation {"
// legacy-line: "  const sources: QualifyingAppointmentSource[] = [];"
// legacy-line: ""
// legacy-line: "  for (const row of snapshot.appointments) {"
// legacy-line: "    const source = selectQualifyingSource(row, evaluationNow);"
// legacy-line: "    if (source) sources.push(source);"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  if (sources.length === 0) {"
// legacy-line: "    return { candidate: null, candidates: [], qualifyingAppointmentIds: new Set() };"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  const ordered = [...sources].sort(compareSourcesForSelection);"
// legacy-line: "  const candidates = ordered.map(buildCandidateFromSource);"
// legacy-line: "  return {"
// legacy-line: "    candidate: candidates[0] ?? null,"
// legacy-line: "    candidates,"
// legacy-line: "    qualifyingAppointmentIds: new Set(sources.map((s) => s.appointmentId)),"
// legacy-line: "  };"
// legacy-line: "}"
// legacy-line: ""
