// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "import { isExpiredBeforeToday } from '../dateUtils';"
// legacy-line: "import { getInventoryAppRoute } from '../knownRoutes';"
// legacy-line: "import { DIALOGUE_ID, PET_DIALOGUE_RULE_VERSION } from '../types';"
// legacy-line: "import type { DialogueCandidate, InsightCandidate } from '../types';"
// legacy-line: "import type { InventorySnapshot, InventorySnapshotBatch, InventorySnapshotItem } from './inventorySnapshotProvider';"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Pure P0 (expired inventory) evaluation over an already-fetched, already"
// legacy-line: " * validated InventorySnapshot — no Supabase access here. See"
// legacy-line: " * inventorySnapshotProvider.ts for the shared fetch and"
// legacy-line: " * expiringSoonInventoryProvider.ts for the P1 evaluator that depends on"
// legacy-line: " * `expiredItemIds` returned below."
// legacy-line: " */"
// legacy-line: ""
// legacy-line: "/** A single item's qualifying expired source — either its earliest"
// legacy-line: " *  qualifying batch, or (only when it has no batch rows at all) the item's"
// legacy-line: " *  own legacy expiry field. */"
// legacy-line: "interface ExpiredSource {"
// legacy-line: "  kind: 'batch' | 'item';"
// legacy-line: "  itemId: string;"
// legacy-line: "  itemName: string | null;"
// legacy-line: "  expiryDate: string;"
// legacy-line: "  createdTime: string | null;"
// legacy-line: "  batchId?: string;"
// legacy-line: "  /** The already-checked (>0) qty this source qualified on — batch `qty` or"
// legacy-line: "   *  item `quantity` — carried through purely for AI Experience Phase 1's"
// legacy-line: "   *  `facts` exposure; never re-derived or re-checked, and never affects"
// legacy-line: "   *  eligibility (that's decided above, in selectExpiredSourceForItem). */"
// legacy-line: "  quantity: number;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/** Structured facts a future Landing Insight / Data-Driven Chat surface can"
// legacy-line: " *  read without re-querying Supabase or reverse-parsing `message`. Every"
// legacy-line: " *  field here is already computed by selectExpiredSourceForItem above —"
// legacy-line: " *  this is a pure exposure of existing values, not a new calculation. */"
// legacy-line: "export interface ExpiredInventoryFacts {"
// legacy-line: "  itemId: string;"
// legacy-line: "  itemName: string | null;"
// legacy-line: "  quantity: number;"
// legacy-line: "  expiryDate: string;"
// legacy-line: "  batchId?: string;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export interface ExpiredInventoryEvaluation {"
// legacy-line: "  candidate: DialogueCandidate | null;"
// legacy-line: "  /** Every independently eligible Expired candidate, in the same business"
// legacy-line: "   *  order compareSourcesForSelection already produces — `candidates[0]` is"
// legacy-line: "   *  always identical to `candidate` above. Additive: existing consumers"
// legacy-line: "   *  that only read `candidate` are unaffected. See"
// legacy-line: "   *  selectFirstEligibleDialogueCandidate in the dialogue layer for how this"
// legacy-line: "   *  is used to skip session-seen/dismissed candidates without changing"
// legacy-line: "   *  business selection order. */"
// legacy-line: "  candidates: DialogueCandidate[];"
// legacy-line: "  /** Every item id with at least one qualifying expired (P0) source — batch"
// legacy-line: "   *  or legacy item-level, not just the globally-selected winner. The P1"
// legacy-line: "   *  evaluator excludes all of these: an already-expired item must never"
// legacy-line: "   *  also show as \"expiring soon\" (P0 represents the more serious state),"
// legacy-line: "   *  even if a *different* batch on the same item would otherwise qualify"
// legacy-line: "   *  for P1. */"
// legacy-line: "  expiredItemIds: Set<string>;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function toNumber(value: number | string | null): number {"
// legacy-line: "  const n = Number(value);"
// legacy-line: "  return Number.isFinite(n) ? n : 0;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function compareBatchesForSelection(a: InventorySnapshotBatch, b: InventorySnapshotBatch): number {"
// legacy-line: "  const aExpiry = a.expiry_date ?? '';"
// legacy-line: "  const bExpiry = b.expiry_date ?? '';"
// legacy-line: "  if (aExpiry !== bExpiry) return aExpiry < bExpiry ? -1 : 1;"
// legacy-line: ""
// legacy-line: "  const aCreated = a.created_at ?? '';"
// legacy-line: "  const bCreated = b.created_at ?? '';"
// legacy-line: "  if (aCreated !== bCreated) return aCreated < bCreated ? -1 : 1;"
// legacy-line: ""
// legacy-line: "  return String(a.id) < String(b.id) ? -1 : 1;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Batch-authoritative rule: if `itemBatches` is non-empty (the item has"
// legacy-line: " * batch records at all), only batch data may produce a candidate for this"
// legacy-line: " * item — the item's own `expiry_date`/`quantity` are never consulted, even"
// legacy-line: " * if no batch currently qualifies. Only an item with zero batch rows falls"
// legacy-line: " * back to the legacy item-level check."
// legacy-line: " */"
// legacy-line: "function selectExpiredSourceForItem("
// legacy-line: "  item: InventorySnapshotItem,"
// legacy-line: "  itemBatches: InventorySnapshotBatch[] | undefined"
// legacy-line: "): ExpiredSource | null {"
// legacy-line: "  if (itemBatches && itemBatches.length > 0) {"
// legacy-line: "    const qualifying = itemBatches.filter((b) => toNumber(b.qty) > 0 && isExpiredBeforeToday(b.expiry_date));"
// legacy-line: "    if (qualifying.length === 0) return null;"
// legacy-line: ""
// legacy-line: "    const earliest = [...qualifying].sort(compareBatchesForSelection)[0];"
// legacy-line: "    return {"
// legacy-line: "      kind: 'batch',"
// legacy-line: "      itemId: item.id,"
// legacy-line: "      itemName: item.name,"
// legacy-line: "      expiryDate: earliest.expiry_date as string,"
// legacy-line: "      createdTime: earliest.created_at,"
// legacy-line: "      batchId: earliest.id,"
// legacy-line: "      quantity: toNumber(earliest.qty),"
// legacy-line: "    };"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  // No batch rows at all — legacy item-level fallback."
// legacy-line: "  if (toNumber(item.quantity) > 0 && isExpiredBeforeToday(item.expiry_date)) {"
// legacy-line: "    return {"
// legacy-line: "      kind: 'item',"
// legacy-line: "      itemId: item.id,"
// legacy-line: "      itemName: item.name,"
// legacy-line: "      expiryDate: item.expiry_date as string,"
// legacy-line: "      createdTime: item.created_at,"
// legacy-line: "      quantity: toNumber(item.quantity),"
// legacy-line: "    };"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  return null;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function compareSourcesForSelection(a: ExpiredSource, b: ExpiredSource): number {"
// legacy-line: "  if (a.expiryDate !== b.expiryDate) return a.expiryDate < b.expiryDate ? -1 : 1;"
// legacy-line: ""
// legacy-line: "  const aCreated = a.createdTime ?? '';"
// legacy-line: "  const bCreated = b.createdTime ?? '';"
// legacy-line: "  if (aCreated !== bCreated) return aCreated < bCreated ? -1 : 1;"
// legacy-line: ""
// legacy-line: "  if (a.itemId !== b.itemId) return a.itemId < b.itemId ? -1 : 1;"
// legacy-line: ""
// legacy-line: "  const aBatch = a.batchId ?? '';"
// legacy-line: "  const bBatch = b.batchId ?? '';"
// legacy-line: "  return aBatch < bBatch ? -1 : aBatch > bBatch ? 1 : 0;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function buildCandidateFromSource(source: ExpiredSource): InsightCandidate<ExpiredInventoryFacts> {"
// legacy-line: "  const safeName = typeof source.itemName === 'string' && source.itemName.trim().length > 0 ? source.itemName.trim() : null;"
// legacy-line: "  const message = safeName"
// legacy-line: "    ? `${safeName} has expired. Please review it now.`"
// legacy-line: "    : 'An inventory item has expired. Please review it now.';"
// legacy-line: "  // messageTemplate is deliberately identical in shape to `message` — the"
// legacy-line: "  // only variation in this candidate's wording is whether a name is known,"
// legacy-line: "  // and `{itemName}` marks exactly that substitution point. `message` above"
// legacy-line: "  // is untouched, byte-for-byte identical to before this refactor."
// legacy-line: "  const messageTemplate = '{itemName} has expired. Please review it now.';"
// legacy-line: ""
// legacy-line: "  const dedupeKey ="
// legacy-line: "    source.kind === 'batch'"
// legacy-line: "      ? `inventory_expired:${source.itemId}:batch:${source.batchId}:${source.expiryDate}`"
// legacy-line: "      : `inventory_expired:${source.itemId}:item:${source.expiryDate}`;"
// legacy-line: ""
// legacy-line: "  const evaluatedAt = new Date().toISOString();"
// legacy-line: "  const facts: ExpiredInventoryFacts = {"
// legacy-line: "    itemId: source.itemId,"
// legacy-line: "    itemName: source.itemName,"
// legacy-line: "    quantity: source.quantity,"
// legacy-line: "    expiryDate: source.expiryDate,"
// legacy-line: "    ...(source.kind === 'batch' ? { batchId: source.batchId } : {}),"
// legacy-line: "  };"
// legacy-line: ""
// legacy-line: "  return {"
// legacy-line: "    app: 'inventory',"
// legacy-line: "    triggerId: DIALOGUE_ID.EXPIRED_INVENTORY,"
// legacy-line: "    facts,"
// legacy-line: "    messageTemplate,"
// legacy-line: "    sourceRecordId: source.itemId,"
// legacy-line: "    evaluatedAt,"
// legacy-line: "    userState: 'ACTIVE_USER_URGENT',"
// legacy-line: "    dialogueId: DIALOGUE_ID.EXPIRED_INVENTORY,"
// legacy-line: "    priority: 'P0',"
// legacy-line: "    message,"
// legacy-line: "    action: { label: 'Check Inventory', route: getInventoryAppRoute() },"
// legacy-line: "    source: {"
// legacy-line: "      app: 'inventory',"
// legacy-line: "      recordId: source.itemId,"
// legacy-line: "      evaluatedAt,"
// legacy-line: "      // Internal provenance only — never rendered in the UI."
// legacy-line: "      ...(source.kind === 'batch' ? { batchId: source.batchId } : {}),"
// legacy-line: "    },"
// legacy-line: "    dedupeKey,"
// legacy-line: "    ruleVersion: PET_DIALOGUE_RULE_VERSION,"
// legacy-line: "    bypassEntryWalk: true,"
// legacy-line: "    eventTime: source.expiryDate,"
// legacy-line: "    createdTime: source.createdTime ?? undefined,"
// legacy-line: "    recordId: source.itemId,"
// legacy-line: "  };"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export function evaluateExpiredInventory(snapshot: InventorySnapshot): ExpiredInventoryEvaluation {"
// legacy-line: "  const sources: ExpiredSource[] = [];"
// legacy-line: ""
// legacy-line: "  for (const item of snapshot.items) {"
// legacy-line: "    const source = selectExpiredSourceForItem(item, snapshot.batchesByItem.get(item.id));"
// legacy-line: "    if (source) sources.push(source);"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  if (sources.length === 0) {"
// legacy-line: "    return { candidate: null, candidates: [], expiredItemIds: new Set() };"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  const ordered = [...sources].sort(compareSourcesForSelection);"
// legacy-line: "  const candidates = ordered.map(buildCandidateFromSource);"
// legacy-line: "  return {"
// legacy-line: "    candidate: candidates[0] ?? null,"
// legacy-line: "    candidates,"
// legacy-line: "    expiredItemIds: new Set(sources.map((s) => s.itemId)),"
// legacy-line: "  };"
// legacy-line: "}"
// legacy-line: ""
