// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "import {"
// legacy-line: "  addCalendarDaysToDateKey,"
// legacy-line: "  daysBetweenDateKeys,"
// legacy-line: "  isWithinInclusiveDateWindow,"
// legacy-line: "  toCalendarDateKey,"
// legacy-line: "} from '../dateUtils';"
// legacy-line: "import { getInventoryAppRoute } from '../knownRoutes';"
// legacy-line: "import { DIALOGUE_ID, PET_DIALOGUE_RULE_VERSION } from '../types';"
// legacy-line: "import type { DialogueCandidate, InsightCandidate } from '../types';"
// legacy-line: "import type { InventorySnapshot, InventorySnapshotBatch, InventorySnapshotItem } from './inventorySnapshotProvider';"
// legacy-line: ""
// legacy-line: "/** See expiredInventoryProvider.ts's ExpiredInventoryFacts for the same"
// legacy-line: " *  design intent. */"
// legacy-line: "export interface ExpiringSoonInventoryFacts {"
// legacy-line: "  itemId: string;"
// legacy-line: "  itemName: string | null;"
// legacy-line: "  quantity: number;"
// legacy-line: "  expiryDate: string;"
// legacy-line: "  daysRemaining: number;"
// legacy-line: "  windowDays: number;"
// legacy-line: "  batchId?: string;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Pure P2 (inventory expiring soon) evaluation over the same"
// legacy-line: " * InventorySnapshot P0 uses — no second Supabase fetch. Mirrors the P0"
// legacy-line: " * batch-authoritative structure in expiredInventoryProvider.ts (an item"
// legacy-line: " * with any batch records is evaluated on batch data only; an item with none"
// legacy-line: " * falls back to its own expiry field) but with the expiring-soon date"
// legacy-line: " * window instead of the expired-before-today check."
// legacy-line: " *"
// legacy-line: " * Runs last in the same-item precedence chain (expired → low stock →"
// legacy-line: " * expiring soon — see inventorySnapshotProvider.ts): excludes any item that"
// legacy-line: " * already qualified for P0, and any item that already qualified for Low"
// legacy-line: " * Stock (Low Stock now outranks Expiring Soon for the same item — see"
// legacy-line: " * lowStockInventoryProvider.ts)."
// legacy-line: " */"
// legacy-line: ""
// legacy-line: "export const INVENTORY_EXPIRING_SOON_DAYS = 30;"
// legacy-line: ""
// legacy-line: "/** A single item's qualifying expiring-soon source — either its earliest"
// legacy-line: " *  qualifying batch, or (only when it has no batch rows at all) the item's"
// legacy-line: " *  own legacy expiry field. */"
// legacy-line: "interface ExpiringSoonSource {"
// legacy-line: "  kind: 'batch' | 'item';"
// legacy-line: "  itemId: string;"
// legacy-line: "  itemName: string | null;"
// legacy-line: "  expiryDate: string;"
// legacy-line: "  createdTime: string | null;"
// legacy-line: "  batchId?: string;"
// legacy-line: "  /** Same intent as expiredInventoryProvider.ts's ExpiredSource.quantity —"
// legacy-line: "   *  the already-checked (>0) qty this source qualified on, carried through"
// legacy-line: "   *  purely for facts exposure. */"
// legacy-line: "  quantity: number;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function toNumber(value: number | string | null): number {"
// legacy-line: "  const n = Number(value);"
// legacy-line: "  return Number.isFinite(n) ? n : 0;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function compareBatchesForSelection(a: InventorySnapshotBatch, b: InventorySnapshotBatch): number {"
// legacy-line: "  const aExpiry = a.expiry_date ?? '';"
// legacy-line: "  const bExpiry = b.expiry_date ?? '';"
// legacy-line: "  if (aExpiry !== bExpiry) return aExpiry < bExpiry ? -1 : 1;"
// legacy-line: ""
// legacy-line: "  const aCreated = a.created_at ?? '';"
// legacy-line: "  const bCreated = b.created_at ?? '';"
// legacy-line: "  if (aCreated !== bCreated) return aCreated < bCreated ? -1 : 1;"
// legacy-line: ""
// legacy-line: "  return String(a.id) < String(b.id) ? -1 : 1;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function selectExpiringSoonSourceForItem("
// legacy-line: "  item: InventorySnapshotItem,"
// legacy-line: "  itemBatches: InventorySnapshotBatch[] | undefined,"
// legacy-line: "  todayKey: string,"
// legacy-line: "  windowEndKey: string"
// legacy-line: "): ExpiringSoonSource | null {"
// legacy-line: "  if (itemBatches && itemBatches.length > 0) {"
// legacy-line: "    // Batch-authoritative, same as P0: an item with any batch rows is"
// legacy-line: "    // evaluated purely on batch data, never item-level fields."
// legacy-line: "    const qualifying = itemBatches.filter("
// legacy-line: "      (b) => toNumber(b.qty) > 0 && isWithinInclusiveDateWindow(b.expiry_date, todayKey, windowEndKey)"
// legacy-line: "    );"
// legacy-line: "    if (qualifying.length === 0) return null;"
// legacy-line: ""
// legacy-line: "    const earliest = [...qualifying].sort(compareBatchesForSelection)[0];"
// legacy-line: "    return {"
// legacy-line: "      kind: 'batch',"
// legacy-line: "      itemId: item.id,"
// legacy-line: "      itemName: item.name,"
// legacy-line: "      expiryDate: earliest.expiry_date as string,"
// legacy-line: "      createdTime: earliest.created_at,"
// legacy-line: "      batchId: earliest.id,"
// legacy-line: "      quantity: toNumber(earliest.qty),"
// legacy-line: "    };"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  // No batch rows at all — legacy item-level fallback."
// legacy-line: "  if (toNumber(item.quantity) > 0 && isWithinInclusiveDateWindow(item.expiry_date, todayKey, windowEndKey)) {"
// legacy-line: "    return {"
// legacy-line: "      kind: 'item',"
// legacy-line: "      itemId: item.id,"
// legacy-line: "      itemName: item.name,"
// legacy-line: "      expiryDate: item.expiry_date as string,"
// legacy-line: "      createdTime: item.created_at,"
// legacy-line: "      quantity: toNumber(item.quantity),"
// legacy-line: "    };"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  return null;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function compareSourcesForSelection(a: ExpiringSoonSource, b: ExpiringSoonSource): number {"
// legacy-line: "  if (a.expiryDate !== b.expiryDate) return a.expiryDate < b.expiryDate ? -1 : 1;"
// legacy-line: ""
// legacy-line: "  const aCreated = a.createdTime ?? '';"
// legacy-line: "  const bCreated = b.createdTime ?? '';"
// legacy-line: "  if (aCreated !== bCreated) return aCreated < bCreated ? -1 : 1;"
// legacy-line: ""
// legacy-line: "  if (a.itemId !== b.itemId) return a.itemId < b.itemId ? -1 : 1;"
// legacy-line: ""
// legacy-line: "  const aBatch = a.batchId ?? '';"
// legacy-line: "  const bBatch = b.batchId ?? '';"
// legacy-line: "  return aBatch < bBatch ? -1 : aBatch > bBatch ? 1 : 0;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function buildMessage(safeName: string | null, daysRemaining: number): string {"
// legacy-line: "  if (daysRemaining === 0) {"
// legacy-line: "    return safeName ? `${safeName} expires today. Please review it.` : 'An inventory item expires today. Please review it.';"
// legacy-line: "  }"
// legacy-line: "  if (daysRemaining === 1) {"
// legacy-line: "    return safeName"
// legacy-line: "      ? `${safeName} will expire tomorrow. Please review it.`"
// legacy-line: "      : 'An inventory item will expire tomorrow. Please review it.';"
// legacy-line: "  }"
// legacy-line: "  return safeName"
// legacy-line: "    ? `${safeName} will expire in ${daysRemaining} days. Please review it.`"
// legacy-line: "    : `An inventory item will expire in ${daysRemaining} days. Please review it.`;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function buildCandidateFromSource(source: ExpiringSoonSource, todayKey: string): InsightCandidate<ExpiringSoonInventoryFacts> {"
// legacy-line: "  const safeName = typeof source.itemName === 'string' && source.itemName.trim().length > 0 ? source.itemName.trim() : null;"
// legacy-line: "  const daysRemaining = Math.max(0, daysBetweenDateKeys(todayKey, source.expiryDate));"
// legacy-line: "  const message = buildMessage(safeName, daysRemaining);"
// legacy-line: "  // buildMessage has three wordings (today/tomorrow/N days) selected purely"
// legacy-line: "  // by `daysRemaining`, which is already exposed in `facts` below — one"
// legacy-line: "  // canonical placeholder template covers all three without altering any of"
// legacy-line: "  // them."
// legacy-line: "  const messageTemplate = '{itemName} will expire in {daysRemaining} days. Please review it.';"
// legacy-line: ""
// legacy-line: "  const dedupeKey ="
// legacy-line: "    source.kind === 'batch'"
// legacy-line: "      ? `inventory_expiring_soon:${source.itemId}:batch:${source.batchId}:${source.expiryDate}:window30`"
// legacy-line: "      : `inventory_expiring_soon:${source.itemId}:item:${source.expiryDate}:window30`;"
// legacy-line: ""
// legacy-line: "  const evaluatedAt = new Date().toISOString();"
// legacy-line: "  const facts: ExpiringSoonInventoryFacts = {"
// legacy-line: "    itemId: source.itemId,"
// legacy-line: "    itemName: source.itemName,"
// legacy-line: "    quantity: source.quantity,"
// legacy-line: "    expiryDate: source.expiryDate,"
// legacy-line: "    daysRemaining,"
// legacy-line: "    windowDays: INVENTORY_EXPIRING_SOON_DAYS,"
// legacy-line: "    ...(source.kind === 'batch' ? { batchId: source.batchId } : {}),"
// legacy-line: "  };"
// legacy-line: ""
// legacy-line: "  return {"
// legacy-line: "    app: 'inventory',"
// legacy-line: "    triggerId: DIALOGUE_ID.INVENTORY_EXPIRING_SOON,"
// legacy-line: "    facts,"
// legacy-line: "    messageTemplate,"
// legacy-line: "    sourceRecordId: source.itemId,"
// legacy-line: "    evaluatedAt,"
// legacy-line: "    userState: 'ACTIVE_USER_URGENT',"
// legacy-line: "    dialogueId: DIALOGUE_ID.INVENTORY_EXPIRING_SOON,"
// legacy-line: "    priority: 'P2',"
// legacy-line: "    message,"
// legacy-line: "    action: { label: 'Check Inventory', route: getInventoryAppRoute() },"
// legacy-line: "    source: {"
// legacy-line: "      app: 'inventory',"
// legacy-line: "      recordId: source.itemId,"
// legacy-line: "      evaluatedAt,"
// legacy-line: "      // Internal provenance only — never rendered in the UI."
// legacy-line: "      ...(source.kind === 'batch' ? { batchId: source.batchId } : {}),"
// legacy-line: "    },"
// legacy-line: "    dedupeKey,"
// legacy-line: "    ruleVersion: PET_DIALOGUE_RULE_VERSION,"
// legacy-line: "    // Unlike P0, P1 neither bypasses the entry walk nor auto-closes — it"
// legacy-line: "    // waits like any ordinary dialogue and stays until dismissed/acted on."
// legacy-line: "    eventTime: source.expiryDate,"
// legacy-line: "    createdTime: source.createdTime ?? undefined,"
// legacy-line: "    recordId: source.itemId,"
// legacy-line: "  };"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export interface ExpiringSoonInventoryEvaluation {"
// legacy-line: "  candidate: DialogueCandidate | null;"
// legacy-line: "  /** Every independently eligible Expiring Soon candidate, in the same"
// legacy-line: "   *  business order compareSourcesForSelection already produces —"
// legacy-line: "   *  `candidates[0]` is always identical to `candidate` above. Additive"
// legacy-line: "   *  only. */"
// legacy-line: "  candidates: DialogueCandidate[];"
// legacy-line: "  /** Every item id with at least one qualifying expiring-soon (P1) source —"
// legacy-line: "   *  batch or legacy item-level, not just the globally-selected winner. The"
// legacy-line: "   *  Low Stock evaluator excludes all of these: an item already flagged as"
// legacy-line: "   *  expiring soon must never also downgrade into a Low Stock candidate,"
// legacy-line: "   *  independent of whether this candidate was the global P1 winner or was"
// legacy-line: "   *  already dismissed/handled in the current session. */"
// legacy-line: "  expiringSoonItemIds: Set<string>;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * `excludedItemIds` is the union of expired (P0) and low-stock (P2)"
// legacy-line: " * qualifying item ids — an item already flagged by either of those must"
// legacy-line: " * never also produce an Expiring Soon candidate, even if a different batch"
// legacy-line: " * on that same item would otherwise qualify."
// legacy-line: " */"
// legacy-line: "export function evaluateExpiringSoonInventory("
// legacy-line: "  snapshot: InventorySnapshot,"
// legacy-line: "  excludedItemIds: Set<string>,"
// legacy-line: "  now: Date = new Date()"
// legacy-line: "): ExpiringSoonInventoryEvaluation {"
// legacy-line: "  const todayKey = toCalendarDateKey(now);"
// legacy-line: "  const windowEndKey = addCalendarDaysToDateKey(todayKey, INVENTORY_EXPIRING_SOON_DAYS);"
// legacy-line: ""
// legacy-line: "  const sources: ExpiringSoonSource[] = [];"
// legacy-line: "  for (const item of snapshot.items) {"
// legacy-line: "    if (excludedItemIds.has(item.id)) continue;"
// legacy-line: "    const source = selectExpiringSoonSourceForItem(item, snapshot.batchesByItem.get(item.id), todayKey, windowEndKey);"
// legacy-line: "    if (source) sources.push(source);"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  if (sources.length === 0) {"
// legacy-line: "    return { candidate: null, candidates: [], expiringSoonItemIds: new Set() };"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  const ordered = [...sources].sort(compareSourcesForSelection);"
// legacy-line: "  const candidates = ordered.map((source) => buildCandidateFromSource(source, todayKey));"
// legacy-line: "  return {"
// legacy-line: "    candidate: candidates[0] ?? null,"
// legacy-line: "    candidates,"
// legacy-line: "    expiringSoonItemIds: new Set(sources.map((s) => s.itemId)),"
// legacy-line: "  };"
// legacy-line: "}"
// legacy-line: ""
