// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "import { supabase } from '@/services/supabaseClient';"
// legacy-line: "import { DIALOGUE_ID, PET_DIALOGUE_RULE_VERSION } from '../types';"
// legacy-line: "import type { DialogueCandidate, InsightCandidate } from '../types';"
// legacy-line: ""
// legacy-line: "/** See expiredInventoryProvider.ts's ExpiredInventoryFacts for the same"
// legacy-line: " *  design intent. `message`/`messageTemplate` intentionally only ever show"
// legacy-line: " *  the first step (`steps[0]`) — the remaining steps are carried separately"
// legacy-line: " *  via `LegacyIntroResult.steps`, exactly as before this refactor. */"
// legacy-line: "export interface LegacyIntroFacts {"
// legacy-line: "  configId: string;"
// legacy-line: "  stepCount: number;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export interface LegacyIntroResult {"
// legacy-line: "  candidate: InsightCandidate<LegacyIntroFacts> | null;"
// legacy-line: "  steps: string[];"
// legacy-line: "  /**"
// legacy-line: "   * The raw `aiboard_simulator_configs.welcome_back_text` value for the"
// legacy-line: "   * same authoritative config row this function already resolves for"
// legacy-line: "   * Legacy Intro — reused here rather than issuing a second"
// legacy-line: "   * `aiboard_simulator_configs` query for Welcome Fallback (see"
// legacy-line: "   * usePersonalizedPetDialogue.ts's buildFallbackCandidate). Three states:"
// legacy-line: "   * `undefined` = the config fetch itself failed/threw/found no row (the"
// legacy-line: "   * caller must fall back to the hardcoded emergency text, since the field"
// legacy-line: "   * is genuinely unknown); `null` = the config row exists but the column is"
// legacy-line: "   * null; a string = whatever raw value is stored (may still be empty/"
// legacy-line: "   * whitespace-only — the caller decides eligibility after trimming, this"
// legacy-line: "   * function never judges \"is this usable\")."
// legacy-line: "   */"
// legacy-line: "  welcomeBackText: string | null | undefined;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Mirrors the existing Post-Login Intro query in CatMascot's legacy"
// legacy-line: " * `initDialog()` effect (module_name='Snabbb.io', is_post_login=true for"
// legacy-line: " * logged-in users). This is an intentional, small duplication of that query"
// legacy-line: " * rather than a shared extraction: the legacy (flag-disabled) code path in"
// legacy-line: " * CatMascot must stay completely untouched by this feature, so its"
// legacy-line: " * Supabase calls are left exactly as they were. See the Phase 1A"
// legacy-line: " * implementation report for this trade-off."
// legacy-line: " *"
// legacy-line: " * Also now the single authoritative source of `welcome_back_text` for the"
// legacy-line: " * Phase-1A Welcome Fallback candidate (see usePersonalizedPetDialogue.ts)."
// legacy-line: " * That column lives on this exact same `aiboard_simulator_configs` row, so"
// legacy-line: " * this function fetches it unconditionally — including when"
// legacy-line: " * `alreadyCompleted` is true, the one case where this function previously"
// legacy-line: " * never queried Supabase at all, and which is precisely when Welcome"
// legacy-line: " * Fallback (a returning-user message) is most likely to actually be shown."
// legacy-line: " * The Legacy Intro candidate itself is still never built/returned once"
// legacy-line: " * `alreadyCompleted` is true — only this added `welcomeBackText` value is."
// legacy-line: " */"
// legacy-line: "export async function fetchLegacyIntroCandidate("
// legacy-line: "  userId: string,"
// legacy-line: "  alreadyCompleted: boolean,"
// legacy-line: "  signal?: AbortSignal"
// legacy-line: "): Promise<LegacyIntroResult> {"
// legacy-line: "  if (!userId) return { candidate: null, steps: [], welcomeBackText: undefined };"
// legacy-line: ""
// legacy-line: "  try {"
// legacy-line: "    const { data: configs, error: configsError } = await supabase"
// legacy-line: "      .from('aiboard_simulator_configs')"
// legacy-line: "      .select('id, welcome_back_text')"
// legacy-line: "      .eq('module_name', 'Snabbb.io')"
// legacy-line: "      .limit(1)"
// legacy-line: "      .abortSignal(signal as AbortSignal);"
// legacy-line: ""
// legacy-line: "    if (configsError || !configs || configs.length === 0) {"
// legacy-line: "      return { candidate: null, steps: [], welcomeBackText: undefined };"
// legacy-line: "    }"
// legacy-line: ""
// legacy-line: "    const configId = configs[0].id;"
// legacy-line: "    const welcomeBackText: string | null = configs[0].welcome_back_text ?? null;"
// legacy-line: ""
// legacy-line: "    if (alreadyCompleted) {"
// legacy-line: "      // Legacy Intro is not eligible for a user who has already completed"
// legacy-line: "      // it — unchanged from before this change — but welcome_back_text was"
// legacy-line: "      // already fetched above from the same row, so it's still returned."
// legacy-line: "      return { candidate: null, steps: [], welcomeBackText };"
// legacy-line: "    }"
// legacy-line: ""
// legacy-line: "    const { data, error } = await supabase"
// legacy-line: "      .from('aiboard_simulator_dialog_steps')"
// legacy-line: "      .select('step_text, sort_order')"
// legacy-line: "      .eq('config_id', configId)"
// legacy-line: "      .eq('is_post_login', true)"
// legacy-line: "      .order('sort_order', { ascending: true })"
// legacy-line: "      .abortSignal(signal as AbortSignal);"
// legacy-line: ""
// legacy-line: "    if (error) return { candidate: null, steps: [], welcomeBackText };"
// legacy-line: ""
// legacy-line: "    const steps = (data || [])"
// legacy-line: "      .map((d: { step_text: unknown }) => d.step_text)"
// legacy-line: "      .filter((text: unknown): text is string => typeof text === 'string' && text.trim().length > 0);"
// legacy-line: ""
// legacy-line: "    if (steps.length === 0) return { candidate: null, steps: [], welcomeBackText };"
// legacy-line: ""
// legacy-line: "    const evaluatedAt = new Date().toISOString();"
// legacy-line: "    const configIdStr = String(configId);"
// legacy-line: "    const facts: LegacyIntroFacts = { configId: configIdStr, stepCount: steps.length };"
// legacy-line: ""
// legacy-line: "    const candidate: InsightCandidate<LegacyIntroFacts> = {"
// legacy-line: "      app: 'legacy',"
// legacy-line: "      triggerId: DIALOGUE_ID.LEGACY_POST_LOGIN_INTRO,"
// legacy-line: "      facts,"
// legacy-line: "      // Deliberately not a `{placeholder}` template: unlike every other"
// legacy-line: "      // trigger, this candidate's rendered text is fully admin-authored"
// legacy-line: "      // content (`aiboard_simulator_dialog_steps.step_text`), not a"
// legacy-line: "      // deterministic-rule-generated string — the canonical template form"
// legacy-line: "      // here is simply the same already-approved first step."
// legacy-line: "      messageTemplate: steps[0],"
// legacy-line: "      sourceRecordId: configIdStr,"
// legacy-line: "      evaluatedAt,"
// legacy-line: "      userState: 'LEGACY_POST_LOGIN_INTRO',"
// legacy-line: "      dialogueId: DIALOGUE_ID.LEGACY_POST_LOGIN_INTRO,"
// legacy-line: "      priority: 'LEGACY_INTRO',"
// legacy-line: "      message: steps[0],"
// legacy-line: "      source: { app: 'aiboard', recordId: configIdStr, evaluatedAt },"
// legacy-line: "      dedupeKey: `legacy_intro:${userId}`,"
// legacy-line: "      ruleVersion: PET_DIALOGUE_RULE_VERSION,"
// legacy-line: "      recordId: configIdStr,"
// legacy-line: "    };"
// legacy-line: ""
// legacy-line: "    return { candidate, steps, welcomeBackText };"
// legacy-line: "  } catch (err) {"
// legacy-line: "    if ((err as { name?: string })?.name === 'AbortError') return { candidate: null, steps: [], welcomeBackText: undefined };"
// legacy-line: "    console.warn('[petDialogue] legacy intro check failed');"
// legacy-line: "    return { candidate: null, steps: [], welcomeBackText: undefined };"
// legacy-line: "  }"
// legacy-line: "}"
// legacy-line: ""
