// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "import { sanitizeTaskTitleForDialogue } from '../safeTaskTitle';"
// legacy-line: "import { getTodoAppRoute } from '../knownRoutes';"
// legacy-line: "import { DIALOGUE_ID, PET_DIALOGUE_RULE_VERSION } from '../types';"
// legacy-line: "import type { DialogueCandidate, InsightCandidate } from '../types';"
// legacy-line: "import type { TodoSnapshot } from './todoSnapshotProvider';"
// legacy-line: "import {"
// legacy-line: "  compareByCreatedTimeThenTaskId,"
// legacy-line: "  extractQualifyingHighUrgencyTaskSource,"
// legacy-line: "  type QualifyingHighUrgencyTaskSource,"
// legacy-line: "} from './todoTaskFilters';"
// legacy-line: ""
// legacy-line: "/** See expiredInventoryProvider.ts's ExpiredInventoryFacts for the same"
// legacy-line: " *  design intent. `urgency` is always 'HIGH' by construction — see"
// legacy-line: " *  todoTaskFilters.ts's extractQualifyingHighUrgencyTaskSource, the only"
// legacy-line: " *  source of QualifyingHighUrgencyTaskSource values. */"
// legacy-line: "export interface OverdueHighTaskFacts {"
// legacy-line: "  taskId: string;"
// legacy-line: "  title: string | null;"
// legacy-line: "  dueDate: string;"
// legacy-line: "  urgency: 'HIGH';"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Pure P0 (overdue High-priority task) evaluation over the TodoSnapshot —"
// legacy-line: " * no Supabase access here. A task qualifies only when its validated date is"
// legacy-line: " * strictly before `localToday`; a task due today is P2 territory"
// legacy-line: " * (taskTodayProvider.ts), never P0 — the `<` vs `===` comparison against"
// legacy-line: " * the same validated date key makes the two mutually exclusive by"
// legacy-line: " * construction, with no separate exclusion set required between them."
// legacy-line: " */"
// legacy-line: ""
// legacy-line: "function compareSourcesForSelection(a: QualifyingHighUrgencyTaskSource, b: QualifyingHighUrgencyTaskSource): number {"
// legacy-line: "  // Oldest overdue date wins first — a task overdue since 2026-08-01"
// legacy-line: "  // outranks one overdue since 2026-08-04."
// legacy-line: "  if (a.validatedDateKey !== b.validatedDateKey) return a.validatedDateKey < b.validatedDateKey ? -1 : 1;"
// legacy-line: ""
// legacy-line: "  // created_at, then task id — see todoTaskFilters.ts for why a"
// legacy-line: "  // missing/malformed created_at must not silently win this tie."
// legacy-line: "  return compareByCreatedTimeThenTaskId(a, b);"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function buildCandidateFromSource(source: QualifyingHighUrgencyTaskSource): InsightCandidate<OverdueHighTaskFacts> {"
// legacy-line: "  const safeTitle = sanitizeTaskTitleForDialogue(source.title);"
// legacy-line: "  const message = safeTitle ? `Your urgent task \"${safeTitle}\" is overdue.` : 'You have an overdue urgent task.';"
// legacy-line: "  const messageTemplate = 'Your urgent task \"{title}\" is overdue.';"
// legacy-line: ""
// legacy-line: "  const evaluatedAt = new Date().toISOString();"
// legacy-line: "  const facts: OverdueHighTaskFacts = {"
// legacy-line: "    taskId: source.taskId,"
// legacy-line: "    title: source.title,"
// legacy-line: "    dueDate: source.validatedDateKey,"
// legacy-line: "    urgency: 'HIGH',"
// legacy-line: "  };"
// legacy-line: ""
// legacy-line: "  return {"
// legacy-line: "    app: 'todo',"
// legacy-line: "    triggerId: DIALOGUE_ID.OVERDUE_HIGH_TASK,"
// legacy-line: "    facts,"
// legacy-line: "    messageTemplate,"
// legacy-line: "    sourceRecordId: source.taskId,"
// legacy-line: "    evaluatedAt,"
// legacy-line: "    userState: 'ACTIVE_USER_URGENT',"
// legacy-line: "    dialogueId: DIALOGUE_ID.OVERDUE_HIGH_TASK,"
// legacy-line: "    priority: 'P0',"
// legacy-line: "    message,"
// legacy-line: "    action: { label: 'View Task', route: getTodoAppRoute() },"
// legacy-line: "    source: {"
// legacy-line: "      app: 'todo',"
// legacy-line: "      recordId: source.taskId,"
// legacy-line: "      evaluatedAt,"
// legacy-line: "    },"
// legacy-line: "    dedupeKey: `overdue_high_task:${source.taskId}:date:${source.validatedDateKey}`,"
// legacy-line: "    ruleVersion: PET_DIALOGUE_RULE_VERSION,"
// legacy-line: "    // Consistent with the existing P0 (expired inventory): overdue is"
// legacy-line: "    // urgent enough to bypass the cosmetic entry walk, and does not"
// legacy-line: "    // auto-close."
// legacy-line: "    bypassEntryWalk: true,"
// legacy-line: "    eventTime: source.validatedDateKey,"
// legacy-line: "    createdTime: source.createdTime ?? undefined,"
// legacy-line: "    recordId: source.taskId,"
// legacy-line: "  };"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export interface OverdueTaskEvaluation {"
// legacy-line: "  candidate: DialogueCandidate | null;"
// legacy-line: "  /** Every independently eligible Overdue High Task candidate, in the same"
// legacy-line: "   *  business order compareSourcesForSelection already produces —"
// legacy-line: "   *  `candidates[0]` is always identical to `candidate` above. Additive"
// legacy-line: "   *  only. */"
// legacy-line: "  candidates: DialogueCandidate[];"
// legacy-line: "  /** Every task id that qualifies as overdue-High, not just the selected"
// legacy-line: "   *  winner — exposed for parity with the inventory evaluators' exclusion"
// legacy-line: "   *  pattern, even though nothing currently needs to exclude by it (P0/P2"
// legacy-line: "   *  are already mutually exclusive by date). */"
// legacy-line: "  qualifyingTaskIds: Set<string>;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export function evaluateOverdueHighTask(snapshot: TodoSnapshot, localToday: string): OverdueTaskEvaluation {"
// legacy-line: "  const sources: QualifyingHighUrgencyTaskSource[] = [];"
// legacy-line: ""
// legacy-line: "  for (const task of snapshot.tasks) {"
// legacy-line: "    const source = extractQualifyingHighUrgencyTaskSource(task);"
// legacy-line: "    if (!source) continue;"
// legacy-line: "    if (source.validatedDateKey < localToday) sources.push(source);"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  if (sources.length === 0) {"
// legacy-line: "    return { candidate: null, candidates: [], qualifyingTaskIds: new Set() };"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  const ordered = [...sources].sort(compareSourcesForSelection);"
// legacy-line: "  const candidates = ordered.map(buildCandidateFromSource);"
// legacy-line: "  return {"
// legacy-line: "    candidate: candidates[0] ?? null,"
// legacy-line: "    candidates,"
// legacy-line: "    qualifyingTaskIds: new Set(sources.map((s) => s.taskId)),"
// legacy-line: "  };"
// legacy-line: "}"
// legacy-line: ""
