// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "import { toValidatedDateKey } from '../dateUtils';"
// legacy-line: "import type { TodoSnapshotTask } from './todoSnapshotProvider';"
// legacy-line: "// `TodoSnapshotTask` is a type-only import — no runtime dependency on the"
// legacy-line: "// Supabase-touching snapshot provider (mirrors expiredInventoryProvider.ts's"
// legacy-line: "// type-only relationship with inventorySnapshotProvider.ts)."
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Shared pure filter for both P0 (overdue) and P2 (due today) High-task"
// legacy-line: " * evaluators — everything except the final date comparison against"
// legacy-line: " * `localToday` is identical between them, so it lives here once rather"
// legacy-line: " * than being duplicated (and risking drift) across two files."
// legacy-line: " *"
// legacy-line: " * Returns `null` for any task that is inactive, not High urgency, or has an"
// legacy-line: " * unusable/malformed date/status/completion field — a malformed *optional*"
// legacy-line: " * field on one task row is never allowed to suppress every other user's"
// legacy-line: " * otherwise-valid urgent task, so the row is simply skipped rather than"
// legacy-line: " * failing the whole provider (mirrors the inventory provider's philosophy:"
// legacy-line: " * pagination/query integrity failures fail the provider, but a single bad"
// legacy-line: " * business-data row does not)."
// legacy-line: " */"
// legacy-line: ""
// legacy-line: "export interface QualifyingHighUrgencyTaskSource {"
// legacy-line: "  taskId: string;"
// legacy-line: "  title: string | null;"
// legacy-line: "  /** Calendar-validated YYYY-MM-DD, never a raw/unvalidated string. */"
// legacy-line: "  validatedDateKey: string;"
// legacy-line: "  createdTime: string | null;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/** `true`/`false` only — anything else (a stray non-boolean value coming"
// legacy-line: " *  through from a loosely-typed Supabase response) is treated as"
// legacy-line: " *  malformed rather than coerced into a boolean. */"
// legacy-line: "function isMalformedCompletionFlag(value: unknown): boolean {"
// legacy-line: "  return value !== null && value !== undefined && typeof value !== 'boolean';"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export function extractQualifyingHighUrgencyTaskSource(task: TodoSnapshotTask): QualifyingHighUrgencyTaskSource | null {"
// legacy-line: "  if (!task.id) return null;"
// legacy-line: ""
// legacy-line: "  if (isMalformedCompletionFlag(task.completed) || isMalformedCompletionFlag(task.is_completed)) return null;"
// legacy-line: "  if (task.completed === true || task.is_completed === true) return null;"
// legacy-line: ""
// legacy-line: "  if (task.status !== null && task.status !== undefined && typeof task.status !== 'string') return null;"
// legacy-line: "  const normalizedStatus = typeof task.status === 'string' ? task.status.trim().toLowerCase() : '';"
// legacy-line: "  if (normalizedStatus === 'done') return null;"
// legacy-line: ""
// legacy-line: "  if (task.urgency !== null && task.urgency !== undefined && typeof task.urgency !== 'string') return null;"
// legacy-line: "  const normalizedUrgency = typeof task.urgency === 'string' ? task.urgency.trim().toUpperCase() : '';"
// legacy-line: "  if (normalizedUrgency !== 'HIGH') return null;"
// legacy-line: ""
// legacy-line: "  const validatedDateKey = toValidatedDateKey(task.date);"
// legacy-line: "  if (!validatedDateKey) return null;"
// legacy-line: ""
// legacy-line: "  return {"
// legacy-line: "    taskId: task.id,"
// legacy-line: "    title: task.title,"
// legacy-line: "    validatedDateKey,"
// legacy-line: "    createdTime: task.created_at,"
// legacy-line: "  };"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "// Lexicographically greater than any real ISO-8601 timestamp string (which"
// legacy-line: "// only ever uses ASCII digits/`-`/`:`/`.`/`T`/`Z`), used as the sentinel"
// legacy-line: "// sort key for a missing/malformed `created_at`. Built via `fromCharCode`"
// legacy-line: "// (U+FFFF) rather than a literal character so this file stays plain ASCII."
// legacy-line: "const MISSING_CREATED_TIME_SORT_SENTINEL = String.fromCharCode(0xffff);"
// legacy-line: ""
// legacy-line: "function createdTimeSortKey(createdTime: string | null): string {"
// legacy-line: "  return createdTime || MISSING_CREATED_TIME_SORT_SENTINEL;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Shared `created_at` → task-id tie-break for both the P0 and P2"
// legacy-line: " * evaluators. A missing/malformed `created_at` is deliberately sorted"
// legacy-line: " * *after* every real timestamp (via the sentinel above) rather than being"
// legacy-line: " * treated as `''`, which would otherwise sort before every real timestamp"
// legacy-line: " * and let a data gap silently win a priority tie it has no real claim to."
// legacy-line: " * The final task-id comparison guarantees a fully deterministic result"
// legacy-line: " * regardless of `created_at` — Supabase response order is never relied on."
// legacy-line: " */"
// legacy-line: "export function compareByCreatedTimeThenTaskId("
// legacy-line: "  a: QualifyingHighUrgencyTaskSource,"
// legacy-line: "  b: QualifyingHighUrgencyTaskSource"
// legacy-line: "): number {"
// legacy-line: "  const aCreated = createdTimeSortKey(a.createdTime);"
// legacy-line: "  const bCreated = createdTimeSortKey(b.createdTime);"
// legacy-line: "  if (aCreated !== bCreated) return aCreated < bCreated ? -1 : 1;"
// legacy-line: ""
// legacy-line: "  return a.taskId < b.taskId ? -1 : a.taskId > b.taskId ? 1 : 0;"
// legacy-line: "}"
// legacy-line: ""
