// LEGACY CAT CODE: inactive; preserved reversibly as JSON-encoded comment lines.
// Active implementation now comes from @mrburdeveloperteam/pet-function/apps/superapp via sharedPet/.
// legacy-line: "import { supabase } from '@/services/supabaseClient';"
// legacy-line: "import type { CandidateProviderFailureReason, CandidateProviderResult, DialogueCandidate } from '../types';"
// legacy-line: "import { evaluateOverdueHighTask } from './overdueTaskProvider';"
// legacy-line: "import { evaluateHighTaskToday } from './taskTodayProvider';"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Fetches the current authenticated user's own `public.tasks` rows."
// legacy-line: " * Deliberately does NOT filter by `.eq('user_id', userId)`: production RLS"
// legacy-line: " * on `public.tasks` (`tasks_select_own`, validated live) already enforces"
// legacy-line: " * `auth.uid() = user_id` as the sole authorization boundary, and removing"
// legacy-line: " * the client-side filter was specifically tested to still return only the"
// legacy-line: " * authenticated user's own rows — an anonymous or unrelated session gets"
// legacy-line: " * zero rows regardless of what this query asks for. `userId` is still"
// legacy-line: " * required to gate the call (no session → no query) and for the caller's"
// legacy-line: " * own de-duplication scoping, just not as an authorization filter here —"
// legacy-line: " * mirrors the identical, already-reviewed inventorySnapshotProvider.ts"
// legacy-line: " * pattern."
// legacy-line: " *"
// legacy-line: " * This is the single shared fetch both P0 (overdue High task) and P2 (High"
// legacy-line: " * task due today) are derived from."
// legacy-line: " */"
// legacy-line: ""
// legacy-line: "export interface TodoSnapshotTask {"
// legacy-line: "  id: string;"
// legacy-line: "  title: string | null;"
// legacy-line: "  status: string | null;"
// legacy-line: "  urgency: string | null;"
// legacy-line: "  date: string | null;"
// legacy-line: "  completed: boolean | null;"
// legacy-line: "  is_completed: boolean | null;"
// legacy-line: "  created_at: string | null;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export interface TodoSnapshot {"
// legacy-line: "  tasks: TodoSnapshotTask[];"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "export interface TodoDialogueEvaluation {"
// legacy-line: "  overdueCandidate: DialogueCandidate | null;"
// legacy-line: "  taskTodayCandidate: DialogueCandidate | null;"
// legacy-line: "  /** Ordered candidate pools, additive alongside the single-winner fields"
// legacy-line: "   *  above — `overdueCandidates[0] === overdueCandidate`, etc. See"
// legacy-line: "   *  overdueTaskProvider.ts / taskTodayProvider.ts for the ordering each"
// legacy-line: "   *  preserves. */"
// legacy-line: "  overdueCandidates: DialogueCandidate[];"
// legacy-line: "  taskTodayCandidates: DialogueCandidate[];"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "const TASK_PAGE_SIZE = 200;"
// legacy-line: "// Safety net against a runaway/non-advancing pagination loop, not a"
// legacy-line: "// correctness truncation — hitting it fails the evaluation rather than"
// legacy-line: "// silently returning a partial task set. 50 pages * 200 rows = 10,000"
// legacy-line: "// tasks, far beyond any real account's task list today."
// legacy-line: "const MAX_TASK_PAGES = 50;"
// legacy-line: "const PROVIDER_TIMEOUT_MS = 10_000;"
// legacy-line: ""
// legacy-line: "/** Thrown internally to carry a specific, typed failure reason up to the"
// legacy-line: " *  single catch site in fetchTodoSnapshot. Never allowed to escape this"
// legacy-line: " *  module. */"
// legacy-line: "class ProviderFailure extends Error {"
// legacy-line: "  readonly reason: CandidateProviderFailureReason;"
// legacy-line: "  constructor(reason: CandidateProviderFailureReason) {"
// legacy-line: "    super(`[petDialogue] todo snapshot failure: ${reason}`);"
// legacy-line: "    this.reason = reason;"
// legacy-line: "  }"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "function isAbortLikeError(err: unknown): boolean {"
// legacy-line: "  return (err as { name?: string })?.name === 'AbortError';"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Fetches every task visible to the current session via deterministic"
// legacy-line: " * keyset pagination (ordered by `id` ascending, no arbitrary total-row"
// legacy-line: " * cap). Any of the following is treated as a failure (never a"
// legacy-line: " * silently-truncated success): a page query error, a cursor that fails to"
// legacy-line: " * advance, a missing row id, a duplicate id across pages, or exceeding"
// legacy-line: " * MAX_TASK_PAGES."
// legacy-line: " */"
// legacy-line: "async function fetchAllVisibleTasks(signal: AbortSignal): Promise<TodoSnapshotTask[]> {"
// legacy-line: "  const tasks: TodoSnapshotTask[] = [];"
// legacy-line: "  const seenIds = new Set<string>();"
// legacy-line: "  let cursor: string | null = null;"
// legacy-line: "  let pageCount = 0;"
// legacy-line: ""
// legacy-line: "  for (;;) {"
// legacy-line: "    if (signal.aborted) throw new DOMException('Aborted', 'AbortError');"
// legacy-line: ""
// legacy-line: "    if (pageCount >= MAX_TASK_PAGES) {"
// legacy-line: "      throw new ProviderFailure('pagination_incomplete');"
// legacy-line: "    }"
// legacy-line: "    pageCount += 1;"
// legacy-line: ""
// legacy-line: "    let query = supabase"
// legacy-line: "      .from('tasks')"
// legacy-line: "      .select('id, title, status, urgency, date, completed, is_completed, created_at')"
// legacy-line: "      .order('id', { ascending: true })"
// legacy-line: "      .limit(TASK_PAGE_SIZE);"
// legacy-line: ""
// legacy-line: "    if (cursor !== null) {"
// legacy-line: "      query = query.gt('id', cursor);"
// legacy-line: "    }"
// legacy-line: ""
// legacy-line: "    const { data, error } = await query.abortSignal(signal);"
// legacy-line: "    if (error) throw new ProviderFailure('item_query_failed');"
// legacy-line: ""
// legacy-line: "    const page = (data || []) as TodoSnapshotTask[];"
// legacy-line: "    if (page.length === 0) break;"
// legacy-line: ""
// legacy-line: "    const lastId = page[page.length - 1]?.id;"
// legacy-line: "    if (!lastId) throw new ProviderFailure('unexpected_data');"
// legacy-line: ""
// legacy-line: "    // `.gt('id', cursor)` should guarantee this server-side; re-checked here"
// legacy-line: "    // as a defensive invariant rather than trusted blindly."
// legacy-line: "    if (cursor !== null && !(lastId > cursor)) {"
// legacy-line: "      throw new ProviderFailure('pagination_incomplete');"
// legacy-line: "    }"
// legacy-line: ""
// legacy-line: "    for (const task of page) {"
// legacy-line: "      if (!task.id) throw new ProviderFailure('unexpected_data');"
// legacy-line: "      if (seenIds.has(task.id)) {"
// legacy-line: "        // A duplicate id across pages means pagination can't be trusted;"
// legacy-line: "        // fail closed rather than risk under- or double-counting."
// legacy-line: "        throw new ProviderFailure('unexpected_data');"
// legacy-line: "      }"
// legacy-line: "      seenIds.add(task.id);"
// legacy-line: "      tasks.push(task);"
// legacy-line: "    }"
// legacy-line: ""
// legacy-line: "    cursor = lastId;"
// legacy-line: ""
// legacy-line: "    if (page.length < TASK_PAGE_SIZE) break; // final partial page — done"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  return tasks;"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "async function fetchTodoSnapshot(userId: string, signal?: AbortSignal): Promise<CandidateProviderResult<TodoSnapshot>> {"
// legacy-line: "  if (!userId) return { status: 'success', candidate: { tasks: [] } };"
// legacy-line: ""
// legacy-line: "  // Same timeout/abort disambiguation as inventorySnapshotProvider.ts: an"
// legacy-line: "  // external abort (unmount/logout/newer-generation) must resolve as"
// legacy-line: "  // `aborted` (apply no result), while a request that's simply taking too"
// legacy-line: "  // long must resolve as `failed` with reason 'timeout' (show the neutral"
// legacy-line: "  // fallback)."
// legacy-line: "  const internalController = new AbortController();"
// legacy-line: "  let timedOut = false;"
// legacy-line: ""
// legacy-line: "  const onExternalAbort = () => internalController.abort();"
// legacy-line: "  if (signal) {"
// legacy-line: "    if (signal.aborted) internalController.abort();"
// legacy-line: "    else signal.addEventListener('abort', onExternalAbort);"
// legacy-line: "  }"
// legacy-line: ""
// legacy-line: "  const timeoutId = setTimeout(() => {"
// legacy-line: "    timedOut = true;"
// legacy-line: "    internalController.abort();"
// legacy-line: "  }, PROVIDER_TIMEOUT_MS);"
// legacy-line: ""
// legacy-line: "  try {"
// legacy-line: "    const tasks = await fetchAllVisibleTasks(internalController.signal);"
// legacy-line: "    return { status: 'success', candidate: { tasks } };"
// legacy-line: "  } catch (err) {"
// legacy-line: "    if (isAbortLikeError(err)) {"
// legacy-line: "      if (signal?.aborted) return { status: 'aborted' };"
// legacy-line: "      if (timedOut) return { status: 'failed', reason: 'timeout' };"
// legacy-line: "      return { status: 'aborted' };"
// legacy-line: "    }"
// legacy-line: "    if (err instanceof ProviderFailure) {"
// legacy-line: "      return { status: 'failed', reason: err.reason };"
// legacy-line: "    }"
// legacy-line: "    console.warn('[petDialogue] todo snapshot fetch failed unexpectedly');"
// legacy-line: "    return { status: 'failed', reason: 'unexpected_data' };"
// legacy-line: "  } finally {"
// legacy-line: "    clearTimeout(timeoutId);"
// legacy-line: "    if (signal) signal.removeEventListener('abort', onExternalAbort);"
// legacy-line: "  }"
// legacy-line: "}"
// legacy-line: ""
// legacy-line: "/**"
// legacy-line: " * Single hook-facing entry point: fetches the Todo snapshot once, then"
// legacy-line: " * derives the P0 (overdue High task) and P2 (High task due today)"
// legacy-line: " * candidates from it. Neither ever triggers a second complete tasks fetch."
// legacy-line: " * The two are mutually exclusive by date comparison inside their own"
// legacy-line: " * evaluators, so no cross-evaluator exclusion set is threaded here (unlike"
// legacy-line: " * the inventory P0/P1/low-stock chain)."
// legacy-line: " */"
// legacy-line: "export async function fetchTodoDialogueEvaluation("
// legacy-line: "  userId: string,"
// legacy-line: "  localToday: string,"
// legacy-line: "  signal?: AbortSignal"
// legacy-line: "): Promise<CandidateProviderResult<TodoDialogueEvaluation>> {"
// legacy-line: "  const snapshotResult = await fetchTodoSnapshot(userId, signal);"
// legacy-line: "  if (snapshotResult.status !== 'success') return snapshotResult;"
// legacy-line: ""
// legacy-line: "  const snapshot = snapshotResult.candidate ?? { tasks: [] };"
// legacy-line: ""
// legacy-line: "  const { candidate: overdueCandidate, candidates: overdueCandidates } = evaluateOverdueHighTask(snapshot, localToday);"
// legacy-line: "  const { candidate: taskTodayCandidate, candidates: taskTodayCandidates } = evaluateHighTaskToday(snapshot, localToday);"
// legacy-line: ""
// legacy-line: "  return {"
// legacy-line: "    status: 'success',"
// legacy-line: "    candidate: { overdueCandidate, taskTodayCandidate, overdueCandidates, taskTodayCandidates },"
// legacy-line: "  };"
// legacy-line: "}"
// legacy-line: ""
